In [1]:
import os # type:ignore # isort:skip # fmt:skip # noqa # nopep8
import sys # type:ignore # isort:skip # fmt:skip # noqa # nopep8
from pathlib import Path # type:ignore # isort:skip # fmt:skip # noqa # nopep8

mod = sys.modules[__name__]

code_dir = None
code_dir_name = 'Code'
unwanted_subdir_name = 'Analysis'

if code_dir_name not in str(Path.cwd()).split('/')[-1]:
    for _ in range(5):

        parent_path = str(Path.cwd().parents[_]).split('/')[-1]

        if (code_dir_name in parent_path) and (unwanted_subdir_name not in parent_path):

            code_dir = str(Path.cwd().parents[_])

            if code_dir is not None:
                break
else:
    code_dir = str(Path.cwd())
sys.path.append(code_dir)

# %load_ext autoreload
# %autoreload 2

In [2]:
from setup_module.imports import * # type:ignore # isort:skip # fmt:skip # noqa # nopep8
from setup_module.estimators_get_pipe import * # type:ignore # isort:skip # fmt:skip # noqa # nopep8

/opt/homebrew/Caskroom/mambaforge/base/envs/Automating_Equity1/lib/python3.10/site-packages/outdated/utils.py:14: OutdatedPackageWarning: The package pingouin is out of date. Your version is 0.5.3, the latest is 0.5.4.
Set the environment variable OUTDATED_IGNORE=1 to disable these warnings.
  return warn(

Using MPS

0it [00:00, ?it/s]

Using MPS

### Set variables

In [3]:
# Variables
t = time.time()
n_jobs = -1
n_splits = 10
n_repeats = 3
random_state = 42
refit = True
class_weight = 'balanced'
cv = RepeatedStratifiedKFold(
    n_splits=n_splits, n_repeats=n_repeats, random_state=random_state
)
scoring = 'recall'
scores = [
    'recall', 'accuracy', 'f1', 'roc_auc',
    'explained_variance', 'matthews_corrcoef'
]
scorers = {
    'precision_score': make_scorer(precision_score, zero_division=0),
    'recall_score': make_scorer(recall_score, zero_division=0),
    'accuracy_score': make_scorer(accuracy_score, zero_division=0),
}
protocol = pickle.HIGHEST_PROTOCOL
analysis_columns = ['Warmth', 'Competence']
text_col = 'Job Description spacy_sentencized'
classified_columns = ['Warmth_Probability', 'Competence_Probability']
metrics_dict = {
    # f'{scoring.title()} Best Score': np.nan,
    # f'{scoring.title()} Best Threshold': np.nan,
    # 'Train - Mean Cross Validation Score': np.nan,
    # f'Train - Mean Cross Validation - {scoring.title()}': np.nan,
    # f'Train - Mean Explained Variance - {scoring.title()}': np.nan,
    # 'Test - Mean Cross Validation Score': np.nan,
    # f'Test - Mean Cross Validation - {scoring.title()}': np.nan,
    # f'Test - Mean Explained Variance - {scoring.title()}': np.nan,
    'Explained Variance': np.nan,
    'Accuracy': np.nan,
    'Balanced Accuracy': np.nan,
    'Precision': np.nan,
    'Average Precision': np.nan,
    'Recall': np.nan,
    'F1-score': np.nan,
    'Matthews Correlation Coefficient': np.nan,
    'Brier Score': np.nan,
    'Fowlkes–Mallows Index': np.nan,
    'R2 Score': np.nan,
    'ROC': np.nan,
    'AUC': np.nan,
    'Log Loss/Cross Entropy': np.nan,
    'Cohen’s Kappa': np.nan,
    'Geometric Mean': np.nan,
    'Classification Report': np.nan,
    'Imbalanced Classification Report': np.nan,
    'Confusion Matrix': np.nan,
    'Normalized Confusion Matrix': np.nan,
}

# Transformer variables
max_length = 512
returned_tensor = 'pt'
cpu_counts = torch.multiprocessing.cpu_count()
device = torch.device('mps') if torch.has_mps and torch.backends.mps.is_built() and torch.backends.mps.is_available(
) else torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
device_name = str(device.type)
print(f'Using {device_name.upper()}')
# Set random seed
random_state = 42
random.seed(random_state)
np.random.seed(random_state)
torch.manual_seed(random_state)
cores = multiprocessing.cpu_count()
torch.Generator(device_name).manual_seed(random_state)
cores = multiprocessing.cpu_count()
accelerator = Accelerator()
torch.autograd.set_detect_anomaly(True)
os.environ.get('TOKENIZERS_PARALLELISM')
os.environ.get('PYTORCH_MPS_HIGH_WATERMARK_RATIO')
os.environ.get('TRANSFORMERS_CACHE')
openai_token = os.environ['OPENAI_API_KEY']
huggingface_token = os.environ['HUGGINGFACE_API_KEY']
# load_in_4bit=True, bnb_4bit_use_double_quant=True, bnb_4bit_compute_dtype=torch.bfloat16, bnb_4bit_quant_type='nf4'
quantization_config_dict = {
    'load_in_8bit': True,
    'llm_int8_skip_modules': ['lm_head'],
}
skip_fitted_estimators = False
evaluate_estimator_on_concat = False
hyperparameter_tuning = False

Using MPS

# Functions

In [4]:
def load_classified_df(
    df, df_name, df_len, done_dfs_name, df_save_dir
):
    print(f'Loading {df_name}_{done_dfs_name}...')
    df = pd.read_pickle(f'{df_save_dir}{df_name}_{done_dfs_name}.pkl')
    print(f'Dataframe {df_name}_{done_dfs_name} loaded with shape: {df.shape}')

    return df

In [5]:
def extract_prediction(text):
    if pred := classifier(text):
        return pd.Series([pred[0]['label'].split('LABEL_')[1], pred[0]['score']])
    else:
        return None, None

In [6]:
class ToDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        # check is encodings and labels are tensors
        for key, val in self.encodings.items():
            if not torch.is_tensor(val[idx]):
                self.encodings[key][idx] = torch.tensor(val[idx], dtype=torch.long, device=device)
        if self.labels is not None and not torch.is_tensor(self.labels[idx]):
            with contextlib.suppress(ValueError):
                self.labels[idx] = torch.tensor(self.labels[idx], dtype=torch.long, device=device)
        item = {key: val[idx].to(device) for key, val in self.encodings.items()}
        if self.labels is not None:
            item['labels'] = self.labels[idx]
        return item

    def __len__(self):
        return len(self.encodings['input_ids'])

In [7]:
class CustomTrainer(Trainer):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.pos_weight = self._calculate_class_weights(self.train_dataset)

    def _calculate_class_weights(self, dataset):
        # Count the number of samples in each class
        class_counts = torch.bincount(torch.tensor(dataset.labels, device=device))

        # Calculate weight and pos_weight
        num_negative = class_counts[0].item()
        num_positive = class_counts[1].item()
        # weight_neg = num_positive / (num_negative + 1e-5)
        weight_pos = num_negative / (num_positive + 1e-5)
        # weight = torch.tensor([weight_neg, weight_pos], device=device)
        pos_weight = torch.tensor([weight_pos], device=device)

        return pos_weight

    def _calculate_calibration_loss(self, logits, labels):
        return torch.nn.BCEWithLogitsLoss(pos_weight=self.pos_weight.to(device))(
            logits.to(device), torch.nn.functional.one_hot(labels, logits.size(-1)).long().float().to(device)
        )

    def compute_loss(self, model, inputs, return_outputs=False):
        labels = inputs.pop('labels').to(device)
        outputs = model(**inputs)
        logits = outputs.get('logits').to(device)
        loss = self._calculate_calibration_loss(logits, labels)
        return (loss, outputs) if return_outputs else loss

In [8]:
# Function to get y_pred and y_pred_prob
def preprocess_logits_for_metrics_from_logits(y_pred_logits, print_enabled=None):

    if print_enabled is None:
        print_enabled = True

    # Get y_pred
    if not torch.is_tensor(y_pred_logits):
        y_pred_logits_tensor = torch.tensor(y_pred_logits, device=device)
    if print_enabled:
        print('-'*20)
        print('Getting y_pred through argmax of y_pred_logits...')
    try:
        y_pred_array = torch.argmax(y_pred_logits_tensor, axis=-1)
        if print_enabled: print('Using torch.argmax.')
    except Exception:
        y_pred_array = y_pred_logits.argmax(axis=-1)
        if print_enabled: print('Using np.argmax.')
    if print_enabled:
        print(f'y_pred_array shape: {y_pred_array.shape}')
        print('-'*20)
        print('Flattening y_pred...')
    y_pred = y_pred_array.flatten().tolist()
    if print_enabled:
        print(f'y_pred length: {len(y_pred)}')
        print('-'*20)

    # Get y_pred_prob
    if print_enabled:
        print('-'*20)
        print('Getting y_pred_prob through sigmoid of y_pred_logits...')
    try:
        y_pred_prob_array = torch.nn.functional.sigmoid(y_pred_logits_tensor)
        if print_enabled: print('Using torch.nn.functional.sigmoid.')
    except Exception:
        y_pred_prob_array = scipy.special.expit(y_pred_logits_tensor, axis=-1)
        if print_enabled: print('Using scipy.special.expit.')
    # from: https://discuss.huggingface.co/t/different-results-predicting-from-trainer-and-model/12922
    assert all(y_pred_prob_array.argmax(axis=-1) == y_pred_array), 'Argmax of y_pred_prob_array does not match y_pred_array.'
    y_pred_prob = y_pred_prob_array[:, -1].flatten().tolist()
    if print_enabled:
        print(f'y_pred_prob shape: {y_pred_prob_array.shape}')
        print('-'*20)
        print('Flattening y_pred_prob and extracting probabilities of 1...')
        print(f'y_pred length: {len(y_pred_prob)}')
        print('-'*20)

    return (
        y_pred_array, y_pred, y_pred_prob_array, y_pred_prob
    )

In [9]:
def prob_confirmatory_tests(y_pred, y_pred_prob):

    # Confirmatory Regression
    print('+'*20)
    print('Confirmatory Tests validating the linear relationship between y_pred and y_pred_prob')
    print('-'*20)
    print('T-Test y_pred_prob ~ y_pred:')
    levene = scipy.stats.levene(y_pred_prob, y_pred)
    equal_var_levene = levene.pvalue < 0.05
    print(scipy.stats.ttest_ind(y_pred_prob, y_pred, equal_var=equal_var_levene))

    print('\n')
    print('-'*20)
    print('Logit y_pred ~ y_pred_prob:')
    try:
        logit_model = sm.Logit(endog=y_pred, exog=y_pred_prob)
        logit_results = logit_model.fit()
        std_coef = logit_results.params[0] / np.std(y_pred_prob)
        std_err = logit_results.bse[0]
        log_likelihood = logit_results.llf
        print(logit_results.summary())
        print('-'*20)
        print(f'Std Coef: {std_coef}')
        print(f'Std Err: {std_err}')
        print(f'Log Likelihood: {log_likelihood}')
    except Exception as e:
        print(type(e).__name__)

    print('-'*20)
    print('\n')
    print('-'*20)
    print('OLS y_pred_prob ~ y_pred:')
    try:
        ols_model = sm.OLS(endog=y_pred_prob, exog=y_pred)
        ols_results = ols_model.fit()
        std_coef = ols_results.params[0] / np.std(y_pred)
        std_err = ols_results.bse[0]
        print(ols_results.summary())
        print('-'*20)
        print(f'Std Coef: {std_coef}')
        print(f'Std Err: {std_err}')
    except Exception as e:
        print(type(e).__name__)

    print('-'*20)
    print('+'*20)
    print('\n')

# Classifying

### READ DATA

In [10]:
# # ATTN: IF THIS IS THE FIRST TIME YOU ARE CLASSIFYING JOBS, UNCOMMENT AND RUN THIS CODE
# with open(f'{data_dir}df_jobs_len.txt', 'r') as f:
#     df_jobs_len = int(f.read())
# df_jobs = pd.read_pickle(f'{df_save_dir}df_jobs_for_classification.pkl')
# assert len(df_jobs) == df_jobs_len, f'DATAFRAME MISSING DATA! DF SHOULD BE OF LENGTH {df_jobs_len} BUT IS OF LENGTH {len(df_jobs)}'
# print(f'Dataframe df_jobs loaded with shape: {df_jobs.shape}')
# with open(f'{data_dir}df_manual_len.txt', 'r') as f:
#     df_manual_len = int(f.read())
# df_manual = pd.read_pickle(f'{df_save_dir}df_manual_for_training.pkl')
# assert len(df_manual) == df_manual_len, f'DATAFRAME MISSING DATA! DF SHOULD BE OF LENGTH {df_manual_len} BUT IS OF LENGTH {len(df_manual)}'
# print(f'Dataframe df_manual loaded with shape: {df_manual.shape}')

In [11]:
with open(f'{data_dir}df_jobs_len.txt', 'r') as f:
    df_jobs_len = int(f.read())

with open(f'{data_dir}df_manual_len.txt', 'r') as f:
    df_manual_len = int(f.read())

for done_dfs_name in ['classified', 'classified_Warmth_Competence', 'classified_Warmth']:
    if (os.path.exists(f'{df_save_dir}df_jobs_{done_dfs_name}.pkl') and os.path.getsize(f'{df_save_dir}df_jobs_{done_dfs_name}.pkl') > 0) and (os.path.exists(f'{df_save_dir}df_manual_{done_dfs_name}.pkl') and os.path.getsize(f'{df_save_dir}df_manual_{done_dfs_name}.pkl') > 0):

        df_jobs = pd.read_pickle(f'{df_save_dir}df_jobs_{done_dfs_name}.pkl')
        assert len(df_jobs) == df_jobs_len, f'DATAFRAME MISSING DATA! DF SHOULD BE OF LENGTH {df_jobs_len} BUT IS OF LENGTH {len(df_jobs)}'
        df_manual = pd.read_pickle(f'{df_save_dir}df_manual_{done_dfs_name}.pkl')

        if (
            done_dfs_name == 'classified'
            and 'Warmth' in df_jobs.columns
            and 'Warmth_Probability' in df_jobs.columns
            and 'Competence' in df_jobs.columns
            and 'Competence_Probability' in df_jobs.columns
        ):
            df_jobs = load_classified_df(df_jobs, 'df_jobs', df_jobs_len, done_dfs_name, df_save_dir)
            df_manual = load_classified_df(df_manual, 'df_manual', df_manual_len, done_dfs_name, df_save_dir)
            break

        elif (
            done_dfs_name == 'classified_Warmth_Competence'
            and 'Warmth' in df_jobs.columns
            and 'Warmth_Probability' in df_jobs.columns
            and 'Competence' in df_jobs.columns
            and 'Competence_Probability' in df_jobs.columns
        ):
            df_jobs = load_classified_df(df_jobs, 'df_jobs', df_jobs_len, done_dfs_name, df_save_dir)
            df_manual = load_classified_df(df_manual, 'df_manual', df_manual_len, done_dfs_name, df_save_dir)
            break

        elif (
            done_dfs_name == 'classified_Warmth'
            and 'Warmth' in df_jobs.columns
            and 'Warmth_Probability' in df_jobs.columns
            and 'Competence' not in df_jobs.columns
            and 'Competence_Probability' not in df_jobs.columns
        ):
            df_jobs = load_classified_df(df_jobs, 'df_jobs', df_jobs_len, done_dfs_name, df_save_dir)
            df_manual = load_classified_df(df_manual, 'df_manual', df_manual_len, done_dfs_name, df_save_dir)
            break

else:
    with open(f'{data_dir}df_jobs_classified_len.txt', 'r') as f:
        df_jobs_len = int(f.read())

    with open(f'{data_dir}df_manual_classified_len.txt', 'r') as f:
        df_manual_len = int(f.read())

    print('Loading df_jobs_for_classification...')
    df_jobs = pd.read_pickle(f'{df_save_dir}df_jobs_for_classification.pkl')
    assert len(df_jobs) == df_jobs_len, f'DATAFRAME MISSING DATA! DF SHOULD BE OF LENGTH {df_jobs_len} BUT IS OF LENGTH {len(df_jobs)}'
    print(f'Dataframe df_jobs_for_classification loaded with shape: {df_jobs.shape}')
    df_manual = pd.read_pickle(f'{df_save_dir}df_manual_for_training.pkl')
    assert len(df_manual) == df_manual_len, f'DATAFRAME MISSING DATA! DF SHOULD BE OF LENGTH {df_manual_len} BUT IS OF LENGTH {len(df_manual)}'
    print(f'Dataframe df_manual_for_training loaded with shape: {df_manual.shape}')

Loading df_jobs_classified...
Dataframe df_jobs_classified loaded with shape: (307154, 95)
Loading df_manual_classified...
Dataframe df_manual_classified loaded with shape: (5084, 79)

In [12]:
%%time
print('#'*40)
print('Starting!')
print('#'*40)

done_cols = ''

for col in tqdm.tqdm(analysis_columns):
    if col not in df_jobs.columns and f'{col}_predicted' not in df_manual.columns:

        if classifier_name in list(classifiers_pipe.keys()):
            method = 'Supervised'

            with open(f'{data_dir}{method}_results_save_path.txt', 'r') as f:
                results_save_path = f.read().strip('\n')
            with open(f'{data_dir}{method}_done_xy_save_path.txt', 'r') as f:
                done_xy_save_path = f.read().strip('\n')

            with open(f'{done_xy_save_path}{method} final_estimators_dict.json', 'r') as f:
                final_estimators_dict = json.load(f)
            final_estimators_dict[col]['path_suffix'] = path_suffix = f' - {col} - {(vectorizer_name := final_estimators_dict[col]["vectorizer_name"])} + {(classifier_name := final_estimators_dict[col]["classifier_name"])} (Save_protocol={protocol})'
            print('-'*20)
            print(f'Final Estimators Dict:\n{final_estimators_dict}')
            print('-'*20)

            with open(f'{done_xy_save_path}{method} training_args_dict - {col} - {vectorizer_name} + {classifier_name}.json', 'r') as f:
                training_args_dict = json.load(f)

            print('-'*20)
            print(f'Using {classifier_name} from {method} pipeline.')
            print('Loading Supervised Estimator.')
            with open(
                f'{results_save_path}{method} Fitted Estimator {path_suffix}.pkl', 'rb'
            ) as f:
                estimator = joblib.load(f)
            print('Done loading Supervised Estimator!')

            print('-'*20)
            print('Classifying data.')
            # df_jobs
            print('Classifying df_jobs.')
            X = np.array(list(df_jobs[text_col].astype('str').values))
            df_jobs[col] = estimator.predict(X)
            if hasattr(estimator, 'predict_proba'):
                # Get the the whole of the last column, which is the  probability of 1, and flatten to list
                df_jobs[f'{col}_Probability'] = estimator.predict_proba(X)[:, -1]
            # df_manual
            print('Classifying df_manual to generate instrumental variables.')
            X_instrument = np.array(list(df_manual[text_col].astype('str').values))
            df_manual[f'{col}_predicted'] = estimator.predict(X_instrument)
            if hasattr(estimator, 'predict_proba'):
                # Get the the whole of the last column, which is the  probability of 1, and flatten to list
                df_manual[f'{col}_Probability_predicted'] = estimator.predict_proba(X_instrument)[:, -1]

            print(f'Done classifying data using {classifier_name} for {col}!')
            print('-'*20)

        elif classifier_name in list(transformers_pipe.keys()):
            method = 'Transformers'

            with open(f'{data_dir}{method}_results_save_path.txt', 'r') as f:
                results_save_path = f.read().strip('\n')
            with open(f'{data_dir}{method}_done_xy_save_path.txt', 'r') as f:
                done_xy_save_path = f.read().strip('\n')

            with open(f'{done_xy_save_path}{method} final_estimators_dict.json', 'r') as f:
                final_estimators_dict = json.load(f)
            final_estimators_dict[col]['path_suffix'] = path_suffix = f' - {col} - {(vectorizer_name := final_estimators_dict[col]["vectorizer_name"])} + {(classifier_name := final_estimators_dict[col]["classifier_name"])} (Save_protocol={protocol})'
            print('-'*20)
            print(f'Final Estimators Dict:\n{final_estimators_dict}')
            print('-'*20)

            with open(f'{done_xy_save_path}{method} training_args_dict - {col} - {vectorizer_name} + {classifier_name}.json', 'r') as f:
                training_args_dict = json.load(f)

            print('-'*20)
            print(f'Using {classifier_name} from {method} pipeline.')
            model = transformers_pipe[classifier_name]['model']
            tokenizer = transformers_pipe[classifier_name]['tokenizer']
            config = transformers_pipe[classifier_name]['config']

            print(f'Loading Fitted Transformer {classifier_name} from pretrained.')
            estimator_dir = f'{results_save_path}{method} Fitted Estimator{path_suffix}.model'
            fitted_estimator = model.from_pretrained(estimator_dir, trust_remote_code=True)
            if hasattr(fitted_estimator, 'to'):
                fitted_estimator = fitted_estimator.to(device)
            tokenizer = tokenizer.from_pretrained(estimator_dir, trust_remote_code=True)
            config = config.from_pretrained(f'{estimator_dir}/config.json', trust_remote_code=True)
            print(f'Done loading Fitted Transformer {classifier_name} from pretrained!')

            # Tokenize df_jobs
            X = df_jobs[text_col].astype('str').values.tolist()
            encodings = tokenizer(
            X, truncation=True, padding=True, max_length=max_length, return_tensors=returned_tensor
            ).to(device)
            dataset = ToDataset(encodings)

            # Tokenize df_manual
            X_instrument = df_manual[text_col].astype('str').values.tolist()
            encodings_instrument = tokenizer(
            X_instrument, truncation=True, padding=True, max_length=max_length, return_tensors=returned_tensor
            ).to(device)
            dataset_instrument = ToDataset(encodings_instrument)

            # Accelerate model
            (
                fitted_estimator, tokenizer, dataset, dataset_instrument
            ) = accelerator.prepare(
                fitted_estimator, tokenizer, dataset, dataset_instrument
            )

            print(f'Getting estimator for {col}.')
            estimator = Trainer(
                model=fitted_estimator,
                tokenizer=tokenizer,
                args=TrainingArguments(**training_args_dict),
            )
            if estimator.place_model_on_device:
                estimator.model.to(device)

            # df_jobs
            print('-'*20)
            print(f'Classifying data using {classifier_name} for {col}.')
            print('Classifying df_jobs.')
            (y_pred_logits, y_labels, metrics) = estimator.predict(dataset)
            y_pred_array, y_pred, y_pred_prob_array, y_pred_prob = preprocess_logits_for_metrics_from_logits(y_pred_logits)

            # Assign to dataframe
            df_jobs[col] = y_pred
            df_jobs[f'{col}_Probability'] = y_pred_prob
            df_jobs[col] = df_jobs[col].astype(int)
            df_jobs[f'{col}_Probability'] = df_jobs[f'{col}_Probability'].astype(float)

            # df_manual
            print('Classifying df_manual to generate instrumental variables.')
            (y_pred_logits_instrument, y_labels_instrument, metrics_instrument) = estimator.predict(dataset_instrument)
            y_pred_array_instrument, y_pred_instrument, y_pred_prob_array_instrument, y_pred_prob_instrument = preprocess_logits_for_metrics_from_logits(y_pred_logits_instrument)

            # Assign to dataframe
            df_manual[f'{col}_predicted'] = y_pred_instrument
            df_manual[f'{col}_Probability_predicted'] = y_pred_prob_instrument
            df_manual[f'{col}_predicted'] = df_manual[f'{col}_predicted'].astype(int)
            df_manual[f'{col}_Probability_predicted'] = df_manual[f'{col}_Probability_predicted'].astype(float)

            print(f'Done classifying data using {classifier_name} for {col}!')
            print('-'*20)

        done_cols += f'_{col}'
        assert len(df_jobs) > 0 and isinstance(df_jobs, pd.DataFrame), f'ERORR: LENGTH OF DF = {len(df_jobs)}'
        # df_jobs
        df_jobs.to_pickle(f'{df_save_dir}df_jobs_classified{done_cols}.pkl')
        df_jobs.to_csv(f'{df_save_dir}df_jobs_classified{done_cols}.csv', index=False)
        # df_manual
        df_manual.to_pickle(f'{df_save_dir}df_manual_classified{done_cols}.pkl')
        df_manual.to_csv(f'{df_save_dir}df_manual_classified{done_cols}.csv', index=False)
    else:
        print('-'*20)
        print(f'Column {col} already exists in dataframe. Skipping.')
        print('-'*20)
    # Confirmatory Regression
    print('='*20)
    print(f'Confirmatory test for df_jobs {col}')
    prob_confirmatory_tests(df_jobs[col].values, df_jobs[f'{col}_Probability'].values)
    print(f'Confirmatory test for df_manual {col}')
    prob_confirmatory_tests(df_manual[col], df_manual[f'{col}_predicted'].values)
    print('='*20)

########################################
Starting!
########################################

  0%|          | 0/2 [00:00<?, ?it/s]

--------------------
Column Warmth already exists in dataframe. Skipping.
--------------------
====================
Confirmatory test for df_jobs Warmth
++++++++++++++++++++
Confirmatory Tests validating the linear relationship between y_pred and y_pred_prob
--------------------
T-Test y_pred_prob ~ y_pred:
TtestResult(statistic=85.36721885824605, pvalue=0.0, df=614306.0)


--------------------
Logit y_pred ~ y_pred_prob:
Optimization terminated successfully.
         Current function value: 0.670171
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:               307154
Model:                          Logit   Df Residuals:                   307153
Method:                           MLE   Df Model:                            0
Date:                Thu, 13 Jun 2024   Pseudo R-squ.:                 -0.2154
Time:                        13:45:16   Log-Likelihood:            -2.0585e+05
converged:                       True   LL-Null:                   -1.6936e+05
Covariance Type:            nonrobust   LLR p-value:                       nan
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.9054      0.008    114.584      0.000       0.890       0.921
==============================================================================
--------------------
Std Coef: 2.471884596757334
Std Err: 0.007901333384493541
Log Likelihood: -205845.82757131173
--------------------


--------------------
OLS y_pred_prob ~ y_pred:
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.802
Model:                            OLS   Adj. R-squared (uncentered):              0.802
Method:                 Least Squares   F-statistic:                          1.242e+06
Date:                Thu, 13 Jun 2024   Prob (F-statistic):                        0.00
Time:                        13:45:17   Log-Likelihood:                          31172.
No. Observations:              307154   AIC:                                 -6.234e+04
Df Residuals:                  307153   BIC:                                 -6.233e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.8968      0.001   1114.414      0.000       0.895       0.898
==============================================================================
Omnibus:                    92149.635   Durbin-Watson:                   1.409
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           217363.375
Skew:                           1.722   Prob(JB):                         0.00
Kurtosis:                       5.264   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
--------------------
Std Coef: 2.0991405324349977
Std Err: 0.0008047639110663234
--------------------
++++++++++++++++++++


Confirmatory test for df_manual Warmth
++++++++++++++++++++
Confirmatory Tests validating the linear relationship between y_pred and y_pred_prob
--------------------
T-Test y_pred_prob ~ y_pred:
TtestResult(statistic=-2.413999633045925, pvalue=0.015796033378415914, df=10166.0)


--------------------
Logit y_pred ~ y_pred_prob:
Optimization terminated successfully.
         Current function value: 0.619694
         Iterations 6

 50%|█████     | 1/2 [00:04<00:04,  4.41s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:                 Warmth   No. Observations:                 5084
Model:                          Logit   Df Residuals:                     5083
Method:                           MLE   Df Model:                            0
Date:                Thu, 13 Jun 2024   Pseudo R-squ.:                -0.01871
Time:                        13:45:17   Log-Likelihood:                -3150.5
converged:                       True   LL-Null:                       -3092.6
Covariance Type:            nonrobust   LLR p-value:                       nan
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             1.7179      0.074     23.086      0.000       1.572       1.864
==============================================================================
--------------------
Std Coef: 3.845719712538717
Std Err: 0.07441300735692674
Log Likelihood: -3150.525627329745
--------------------


--------------------
OLS y_pred_prob ~ y_pred:
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.666
Model:                            OLS   Adj. R-squared (uncentered):              0.666
Method:                 Least Squares   F-statistic:                          1.016e+04
Date:                Thu, 13 Jun 2024   Prob (F-statistic):                        0.00
Time:                        13:45:17   Log-Likelihood:                         -1144.3
No. Observations:                5084   AIC:                                      2291.
Df Residuals:                    5083   BIC:                                      2297.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Warmth         0.7861      0.008    100.787      0.000       0.771       0.801
==============================================================================
Omnibus:                      573.436   Durbin-Watson:                   1.837
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5418.415
Skew:                           0.071   Prob(JB):                         0.00
Kurtosis:                       8.056   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
--------------------
Std Coef: 1.7203371418930313
Std Err: 0.007799506142907048
--------------------
++++++++++++++++++++


====================
--------------------
Column Competence already exists in dataframe. Skipping.
--------------------
====================
Confirmatory test for df_jobs Competence
++++++++++++++++++++
Confirmatory Tests validating the linear relationship between y_pred and y_pred_prob
--------------------
T-Test y_pred_prob ~ y_pred:
TtestResult(statistic=-21.700466671508952, pvalue=2.223469186472757e-104, df=614306.0)


--------------------
Logit y_pred ~ y_pred_prob:
Optimization terminated successfully.
         Current function value: 0.505762
         Iterations 6

100%|██████████| 2/2 [00:05<00:00,  2.84s/it]

                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:               307154
Model:                          Logit   Df Residuals:                   307153
Method:                           MLE   Df Model:                            0
Date:                Thu, 13 Jun 2024   Pseudo R-squ.:                  0.2690
Time:                        13:45:18   Log-Likelihood:            -1.5535e+05
converged:                       True   LL-Null:                   -2.1252e+05
Covariance Type:            nonrobust   LLR p-value:                       nan
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             2.6697      0.010    262.497      0.000       2.650       2.690
==============================================================================
--------------------
Std Coef: 7.061947974069714
Std Err: 0.010170227567633736
Log Likelihood: -155346.88954043572
--------------------


--------------------
OLS y_pred_prob ~ y_pred:
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.939
Model:                            OLS   Adj. R-squared (uncentered):              0.939
Method:                 Least Squares   F-statistic:                          4.762e+06
Date:                Thu, 13 Jun 2024   Prob (F-statistic):                        0.00
Time:                        13:45:18   Log-Likelihood:                      1.5779e+05
No. Observations:              307154   AIC:                                 -3.156e+05
Df Residuals:                  307153   BIC:                                 -3.156e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.8270      0.000   2182.302      0.000       0.826       0.828
==============================================================================
Omnibus:                    57269.860   Durbin-Watson:                   1.648
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           159155.390
Skew:                           1.000   Prob(JB):                         0.00
Kurtosis:                       5.905   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
--------------------
Std Coef: 1.6561299605036848
Std Err: 0.00037897271670675535
--------------------
++++++++++++++++++++


Confirmatory test for df_manual Competence
++++++++++++++++++++
Confirmatory Tests validating the linear relationship between y_pred and y_pred_prob
--------------------
T-Test y_pred_prob ~ y_pred:
TtestResult(statistic=0.8331732293355766, pvalue=0.4047666122342374, df=10165.99869941767)


--------------------
Logit y_pred ~ y_pred_prob:
Optimization terminated successfully.
         Current function value: 0.499337
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:             Competence   No. Observations:                 5084
Model:                          Logit   Df Residuals:                     5083
Method:                           MLE   Df Model:                            0
Date:                Thu, 13 Jun 2024   Pseudo R-squ.:                  0.2795
Time:                        13:45:18   Log-Likelihood:                -2538.6
converged:                       True   LL-Null:                       -3523.5
Covariance Type:            nonrobust   LLR p-value:                       nan
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1             2.2395      0.066     33.797      0.000       2.110       2.369
==============================================================================
--------------------
Std Coef: 4.481057111044581
Std Err: 0.06626392862683404
Log Likelihood: -2538.6292636883077
--------------------


--------------------
OLS y_pred_prob ~ y_pred:
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.830
Model:                            OLS   Adj. R-squared (uncentered):              0.830
Method:                 Least Squares   F-statistic:                          2.483e+04
Date:                Thu, 13 Jun 2024   Prob (F-statistic):                        0.00
Time:                        13:45:18   Log-Likelihood:                         -1021.4
No. Observations:                5084   AIC:                                      2045.
Df Residuals:                    5083   BIC:                                      2051.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Competence     0.9185      0.006    157.572      0.000       0.907       0.930
==============================================================================
Omnibus:                      793.080   Durbin-Watson:                   1.706
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            12292.954
Skew:                           0.203   Prob(JB):                         0.00
Kurtosis:                      10.607   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
--------------------
Std Coef: 1.837120858188315
Std Err: 0.005828927707290879
--------------------
++++++++++++++++++++


====================
CPU times: user 15.4 s, sys: 1.92 s, total: 17.3 s
Wall time: 5.71 s

## Inspect classified data

In [13]:
assert len(df_jobs) > 0 and isinstance(df_jobs, pd.DataFrame) and all(col in df_jobs.columns for col in dvs_all), f'ERORR: LENGTH OF DF = {len(df_jobs)}'

df_jobs.to_pickle(f'{df_save_dir}df_jobs_classified.pkl')
df_jobs.to_csv(f'{df_save_dir}df_jobs_classified.csv', index=False)

with open(f'{data_dir}df_jobs_classified_len.txt', 'w') as f:
    f.write(str(len(df_jobs)))

In [14]:
with open(f'{data_dir}df_jobs_classified_len.txt', 'r') as f:
    df_jobs_len = int(f.read())

df_jobs = pd.read_pickle(f'{df_save_dir}df_jobs_classified.pkl')
assert len(df_jobs) == df_jobs_len and all(col in df_jobs.columns for col in dvs_all), f'DATAFRAME MISSING DATA! DF SHOULD BE OF LENGTH {df_jobs_len} BUT IS OF LENGTH {len(df_jobs)}'

In [15]:
assert len(df_manual) > 0 and isinstance(df_manual, pd.DataFrame) and all(col in df_manual.columns for col in dvs_all_predicted), f'ERORR: LENGTH OF DF = {len(df_manual)}'

df_manual.to_pickle(f'{df_save_dir}df_manual_classified.pkl')
df_manual.to_csv(f'{df_save_dir}df_manual_classified.csv', index=False)

with open(f'{data_dir}df_manual_classified_len.txt', 'w') as f:
    f.write(str(len(df_manual)))

In [16]:
with open(f'{data_dir}df_manual_classified_len.txt', 'r') as f:
    df_manual_len = int(f.read())

df_manual = pd.read_pickle(f'{df_save_dir}df_manual_classified.pkl')
assert len(df_manual) == df_manual_len and all(col in df_manual.columns for col in dvs_all_predicted), f'DATAFRAME MISSING DATA! DF SHOULD BE OF LENGTH {df_manual_len} BUT IS OF LENGTH {len(df_manual)}'

In [17]:
df_jobs.head()

  Search Keyword Platform        Job ID                  Job Title             Company Name   Location                   Job Description                    Rating Employment Type                    Company URL                                          Job URL                           Job Age       Job Age Number  Collection Date  Data Row Tracking ID Industry Job Date Type of ownership Language Dutch Requirement in Job Ad English Requirement in Job Ad  Dutch Requirement in Job Ad_No  Dutch Requirement in Job Ad_Yes  English Requirement in Job Ad_No  English Requirement in Job Ad_Yes Sector Code        Sector         Keywords Count  Gender_Female_n  Gender_Female_% per Sector  Gender_Female_% per Social Category  Gender_Female_% per Workforce  Gender_Male_n  Gender_Male_% per Sector  Gender_Male_% per Social Category  Gender_Male_% per Workforce     Gender     Age_Older_n  Age_Older_% per Sector  Age_Older_% per Social Category  Age_Older_% per Workforce  Age_Younger_n  Age_Younger_% per Sector  Age_Younger_% per Social Category  Age_Younger_% per Workforce    Age      Sector_n  % Sector per Workforce  Sector Job Advertisement Count  Sector Gender Designation Job Advertisement Count  Sector Age Designation Job Advertisement Count  Gender_Female  Gender_Male  Gender_Mixed  Age_Mixed  Age_Older  Age_Younger  Gender_Num  Age_Num  Interaction_Female_Older_% per Sector  Interaction_Female_Younger_% per Sector  Interaction_Male_Older_% per Sector  Interaction_Male_Younger_% per Sector  Platform_Num  Platform_LinkedIn  Platform_Indeed  Platform_Glassdoor         Job Description spacy_sentencized           Job Description spacy_sentencized_num_words  Job Description spacy_sentencized_num_unique_words  Job Description spacy_sentencized_num_chars  Job Description spacy_sentencized_num_chars_no_whitespact_and_punt  Job Description spacy_sentencized_num_punctuations  Job Description_num_words  Job Description_num_unique_words  Job Description_num_chars  Job Description_num_chars_no_whitespact_and_punt  Job Description_num_punctuations      Job Description spacy_sentencized_lower       Dutch Requirement in Sentence English Requirement in Sentence  Dutch Requirement in Sentence_No  Dutch Requirement in Sentence_Yes  English Requirement in Sentence_No  English Requirement in Sentence_Yes          Job Description spacy_tokenized               Job Description spacy_sentencized_cleaned                Job Description nltk_tokenized                    Job Description gensim_tokenized                    Job Description bert_tokenized            Warmth  Warmth_Probability  Competence  Competence_Probability
0    wholesale    Indeed   pj_da9f2c12243d7031  Transaction Monitoring Expert  Michael Page   Amsterdam  About Our Client\nThe Global KYC organisation ...  -1.000        -1        https://indeed.nl/rc/clk?jk=da9f2c12243d7031&f...  https://nl.indeed.com/vacature-bekijken/pagead...  2 dagen geleden  2 dagen geleden    2021-01-24      NaN         NaN       NaN      NaN           NaN          en                 No                           No                              1                               0                                 1                                 0                       G      Commercial services      11.000         3421.000                43.135                          28.468                            13.538                4510.000              56.865                        34.038                          17.847             Mixed Gender   2704.000            34.094                      25.435                        10.700              5228.000              65.919                        35.735                          20.689             Mixed Age  7931.000          31.385                       1787                                     6664                                              11464                            0             0             1           1          0           0            1         1                   1470.631                                2843.366                               1938.775                              3748.489                       1               0                 1                  0                                           About Our Client                       3                                               3                                                16                                              14                                                                  0                                      558                            320                          3876                                   3240                                       23                                                  about our client               No                             No                                1                                 0                                   1                                   0                                                [about, our, client]                                   about our client                                           [client]                                           [client]                               [about, our, client]     0          0.012              0              0.015
1    wholesale    Indeed   pj_da9f2c12243d7031  Transaction Monitoring Expert  Michael Page   Amsterdam  About Our Client\nThe Global KYC organisation ...  -1.000        -1        https://indeed.nl/rc/clk?jk=da9f2c12243d7031&f...  https://nl.indeed.com/vacature-bekijken/pagead...  2 dagen geleden  2 dagen geleden    2021-01-24      NaN         NaN       NaN      NaN           NaN          en                 No                           No                              1                               0                                 1                                 0                       G      Commercial services      11.000         3421.000                43.135                          28.468                            13.538                4510.000              56.865                        34.038                          17.847             Mixed Gender   2704.000            34.094                      25.435                        10.700              5228.000              65.919                        35.735                          20.689             Mixed Age  7931.000          31.385                       1787                                     6664                                              11464                            0             0             1           1          0           0            1         1                   1470.631                                2843.366                               1938.775                              3748.489                       1               0                 1                  0          The Global KYC organisation is part of ING's C...                      10                                              10                                                56                                              45                                                                  1                                      558                            320                          3876                                   3240                                       23                 the global kyc organisation is part of ing's c...               No                             No                                1                                 0                                   1                                   0                   [the, global, kyc, organisation, is, part, of,...  the global kyc organisation is part of ing 's ...  [global, kyc, organisation, part, ing, 's, coo...           [global, kyc, organis, ing, coo, domain]  [the, global, ky, ##c, organisation, is, part,...     0          0.014              0              0.059
2    wholesale    Indeed   pj_da9f2c12243d7031  Transaction Monitoring Expert  Michael Page   Amsterdam  About Our Client\nThe Global KYC organisation ...  -1.000        -1        https://indeed.nl/rc/clk?jk=da9f2c12243d7031&f...  https://nl.indeed.com/vacature-bekijken/pagead...  2 dagen geleden  2 dagen geleden    2021-01-24      NaN         NaN       NaN      NaN           NaN          en                 No                           No                              1                               0                                 1                                 0                       G      Commercial services      11.000         3421.000                43.135                          28.468                            13.538                4510.000              56.865                        34.038                          17.847             Mixed Gender   2704.000            34.094                      25.435                        10.700              5228.000              65.919                        35.735                          20.689             Mixed Age  7931.000          31.385                       1787                                     6664                                              11464                            0             0             1           1          0           0            1         1                   1470.631                                2843.366                               1938.775                              3748.489                       1               0                 1                  0          Its purpose is Enabling people and organisatio...                      20                                              19                                               131                                             111                                                                  1                                      558                            320                          3876                                   3240                                       23                 its purpose is enabling people and organisatio...               No                             No                                1                                 0                                   1                                   0                   [its, purpose, is, enabling, people, and, orga...  its purpose is enabling people and organisatio...  [purpose, enabling, people, organisations, use...  [purpos, enabl, peopl, organis, us, bank, serv...  [its, purpose, is, enabling, people, and, orga...     0          0.291              1              0.637
3    wholesale    Indeed   pj_da9f2c12243d7031  Transaction Monitoring Expert  Michael Page   Amsterdam  About Our Client\nThe Global KYC organisation ...  -1.000        -1        https://indeed.nl/rc/clk?jk=da9f2c12243d7031&f...  https://nl.indeed.com/vacature-bekijken/pagead...  2 dagen geleden  2 dagen geleden    2021-01-24      NaN         NaN       NaN      NaN           NaN          en                 No                           No                              1                               0                                 1                                 0                       G      Commercial services      11.000         3421.000                43.135                          28.468                            13.538                4510.000              56.865                        34.038                          17.847             Mixed Gender   2704.000            34.094                      25.435                        10.700              5228.000              65.919                        35.735                          20.689             Mixed Age  7931.000          31.385                       1787                                     6664                                              11464                            0             0             1           1          0           0            1         1                   1470.631                                2843.366                               1938.775                              3748.489                       1               0                 1                  0          Our Global KYC organisation is a first line of...                      34                                              31                                               239                                             203                                                                  1                                      558                            320                          3876                                   3240                                       23                 our global kyc organisation is a first line of...               No                             No                                1                                 0                                   1                                   0                   [our, global, kyc, organisation, is, a, first,...  our global kyc organisation is a first line of...  [global, kyc, organisation, first, line, defen...  [global, kyc, organis, line, defenc, depart, p...  [our, global, ky, ##c, organisation, is, a, fi...     0          0.163              1              0.924
4    wholesale    Indeed   pj_da9f2c12243d7031  Transaction Monitoring Expert  Michael Page   Amsterdam  About Our Client\nThe Global KYC organisation ...  -1.000        -1        https://indeed.nl/rc/clk?jk=da9f2c12243d7031&f...  https://nl.indeed.com/vacature-bekijken/pagead...  2 dagen geleden  2 dagen geleden    2021-01-24      NaN         NaN       NaN      NaN           NaN          en                 No                           No                              1                               0                                 1                                 0                       G      Commercial services      11.000         3421.000                43.135                          28.468                            13.538                4510.000              56.865                        34.038                          17.847             Mixed Gender   2704.000            34.094                      25.435                        10.700              5228.000              65.919                        35.735                          20.689             Mixed Age  7931.000          31.385                       1787                                     6664                                              11464                            0             0             1           1          0           0            1         1                   1470.631                                2843.366                               1938.775                              3748.489                       1               0                 1                  0          In our Global KYC organisation you will be wor...                      18                                              18                                               128                                             109                                                                  1                                      558                            320                          3876                                   3240                                       23                 in our global kyc organisation you will be wor...               No                             No                                1                                 0                                   1                                   0                   [in, our, global, kyc, organisation, you, will...  in our global kyc organisation you will be wor...  [global, kyc, organisation, working, many, col...  [global, kyc, organis, work, colleagu, differ,...  [in, our, global, ky, ##c, organisation, you, ...     1          0.851              0              0.062

In [18]:
df_jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307154 entries, 0 to 307153
Data columns (total 95 columns):
 #   Column                                                              Non-Null Count   Dtype
---  ------                                                              --------------   -----
 0   Search Keyword                                                      307154 non-null  object
 1   Platform                                                            307154 non-null  object
 2   Job ID                                                              307154 non-null  object
 3   Job Title                                                           307154 non-null  object
 4   Company Name                                                        307149 non-null  object
 5   Location                                                            307154 non-null  object
 6   Job Description                                                     307154 non-null  object
 7   Rating                                                              165831 non-null  float64
 8   Employment Type                                                     281052 non-null  object
 9   Company URL                                                         300561 non-null  object
 10  Job URL                                                             307154 non-null  object
 11  Job Age                                                             307154 non-null  object
 12  Job Age Number                                                      307154 non-null  object
 13  Collection Date                                                     307154 non-null  object
 14  Data Row                                                            141182 non-null  float64
 15  Tracking ID                                                         141182 non-null  object
 16  Industry                                                            167425 non-null  object
 17  Job Date                                                            141323 non-null  object
 18  Type of ownership                                                   26102 non-null   object
 19  Language                                                            307154 non-null  object
 20  Dutch Requirement in Job Ad                                         307154 non-null  object
 21  English Requirement in Job Ad                                       307154 non-null  object
 22  Dutch Requirement in Job Ad_No                                      307154 non-null  int64
 23  Dutch Requirement in Job Ad_Yes                                     307154 non-null  int64
 24  English Requirement in Job Ad_No                                    307154 non-null  int64
 25  English Requirement in Job Ad_Yes                                   307154 non-null  int64
 26  Sector Code                                                         307154 non-null  object
 27  Sector                                                              307154 non-null  object
 28  Keywords Count                                                      307154 non-null  float64
 29  Gender_Female_n                                                     307154 non-null  float64
 30  Gender_Female_% per Sector                                          307154 non-null  float64
 31  Gender_Female_% per Social Category                                 307154 non-null  float64
 32  Gender_Female_% per Workforce                                       307154 non-null  float64
 33  Gender_Male_n                                                       307154 non-null  float64
 34  Gender_Male_% per Sector                                            307154 non-null  float64
 35  Gender_Male_% per Social Category                                   307154 non-null  float64
 36  Gender_Male_% per Workforce                                         307154 non-null  float64
 37  Gender                                                              307154 non-null  object
 38  Age_Older_n                                                         307154 non-null  float64
 39  Age_Older_% per Sector                                              307154 non-null  float64
 40  Age_Older_% per Social Category                                     307154 non-null  float64
 41  Age_Older_% per Workforce                                           307154 non-null  float64
 42  Age_Younger_n                                                       307154 non-null  float64
 43  Age_Younger_% per Sector                                            307154 non-null  float64
 44  Age_Younger_% per Social Category                                   307154 non-null  float64
 45  Age_Younger_% per Workforce                                         307154 non-null  float64
 46  Age                                                                 307154 non-null  object
 47  Sector_n                                                            307154 non-null  float64
 48  % Sector per Workforce                                              307154 non-null  float64
 49  Sector Job Advertisement Count                                      307154 non-null  int64
 50  Sector Gender Designation Job Advertisement Count                   307154 non-null  int64
 51  Sector Age Designation Job Advertisement Count                      307154 non-null  int64
 52  Gender_Female                                                       307154 non-null  int64
 53  Gender_Male                                                         307154 non-null  int64
 54  Gender_Mixed                                                        307154 non-null  int64
 55  Age_Mixed                                                           307154 non-null  int64
 56  Age_Older                                                           307154 non-null  int64
 57  Age_Younger                                                         307154 non-null  int64
 58  Gender_Num                                                          307154 non-null  int64
 59  Age_Num                                                             307154 non-null  int64
 60  Interaction_Female_Older_% per Sector                               307154 non-null  float64
 61  Interaction_Female_Younger_% per Sector                             307154 non-null  float64
 62  Interaction_Male_Older_% per Sector                                 307154 non-null  float64
 63  Interaction_Male_Younger_% per Sector                               307154 non-null  float64
 64  Platform_Num                                                        307154 non-null  int64
 65  Platform_LinkedIn                                                   307154 non-null  int64
 66  Platform_Indeed                                                     307154 non-null  int64
 67  Platform_Glassdoor                                                  307154 non-null  int64
 68  Job Description spacy_sentencized                                   307154 non-null  object
 69  Job Description spacy_sentencized_num_words                         307154 non-null  int64
 70  Job Description spacy_sentencized_num_unique_words                  307154 non-null  int64
 71  Job Description spacy_sentencized_num_chars                         307154 non-null  int64
 72  Job Description spacy_sentencized_num_chars_no_whitespact_and_punt  307154 non-null  int64
 73  Job Description spacy_sentencized_num_punctuations                  307154 non-null  int64
 74  Job Description_num_words                                           307154 non-null  int64
 75  Job Description_num_unique_words                                    307154 non-null  int64
 76  Job Description_num_chars                                           307154 non-null  int64
 77  Job Description_num_chars_no_whitespact_and_punt                    307154 non-null  int64
 78  Job Description_num_punctuations                                    307154 non-null  int64
 79  Job Description spacy_sentencized_lower                             307154 non-null  object
 80  Dutch Requirement in Sentence                                       307154 non-null  category
 81  English Requirement in Sentence                                     307154 non-null  category
 82  Dutch Requirement in Sentence_No                                    307154 non-null  int64
 83  Dutch Requirement in Sentence_Yes                                   307154 non-null  int64
 84  English Requirement in Sentence_No                                  307154 non-null  int64
 85  English Requirement in Sentence_Yes                                 307154 non-null  int64
 86  Job Description spacy_tokenized                                     307154 non-null  object
 87  Job Description spacy_sentencized_cleaned                           307154 non-null  object
 88  Job Description nltk_tokenized                                      307154 non-null  object
 89  Job Description gensim_tokenized                                    307154 non-null  object
 90  Job Description bert_tokenized                                      307154 non-null  object
 91  Warmth                                                              307154 non-null  int64
 92  Warmth_Probability                                                  307154 non-null  float64
 93  Competence                                                          307154 non-null  int64
 94  Competence_Probability                                              307154 non-null  float64
dtypes: category(2), float64(27), int64(35), object(31)
memory usage: 218.5+ MB

In [19]:
df_jobs.describe()

        Rating    Data Row   Dutch Requirement in Job Ad_No  Dutch Requirement in Job Ad_Yes  English Requirement in Job Ad_No  English Requirement in Job Ad_Yes  Keywords Count  Gender_Female_n  Gender_Female_% per Sector  Gender_Female_% per Social Category  Gender_Female_% per Workforce  Gender_Male_n  Gender_Male_% per Sector  Gender_Male_% per Social Category  Gender_Male_% per Workforce  Age_Older_n  Age_Older_% per Sector  Age_Older_% per Social Category  Age_Older_% per Workforce  Age_Younger_n  Age_Younger_% per Sector  Age_Younger_% per Social Category  Age_Younger_% per Workforce  Sector_n   % Sector per Workforce  Sector Job Advertisement Count  Sector Gender Designation Job Advertisement Count  Sector Age Designation Job Advertisement Count  Gender_Female  Gender_Male  Gender_Mixed  Age_Mixed  Age_Older  Age_Younger  Gender_Num   Age_Num   Interaction_Female_Older_% per Sector  Interaction_Female_Younger_% per Sector  Interaction_Male_Older_% per Sector  Interaction_Male_Younger_% per Sector  Platform_Num  Platform_LinkedIn  Platform_Indeed  Platform_Glassdoor  Job Description spacy_sentencized_num_words  Job Description spacy_sentencized_num_unique_words  Job Description spacy_sentencized_num_chars  Job Description spacy_sentencized_num_chars_no_whitespact_and_punt  Job Description spacy_sentencized_num_punctuations  Job Description_num_words  Job Description_num_unique_words  Job Description_num_chars  Job Description_num_chars_no_whitespact_and_punt  Job Description_num_punctuations  Dutch Requirement in Sentence_No  Dutch Requirement in Sentence_Yes  English Requirement in Sentence_No  English Requirement in Sentence_Yes   Warmth    Warmth_Probability  Competence  Competence_Probability
count 165831.000 141182.000            307154.000                      307154.000                        307154.000                        307154.000                307154.000      307154.000             307154.000                      307154.000                        307154.000             307154.000           307154.000                    307154.000                      307154.000           307154.000         307154.000                  307154.000                    307154.000           307154.000           307154.000                    307154.000                      307154.000          307154.000        307154.000                  307154.000                               307154.000                                        307154.000                     307154.000    307154.000    307154.000  307154.000 307154.000  307154.000   307154.000 307154.000               307154.000                              307154.000                             307154.000                            307154.000                 307154.000      307154.000        307154.000         307154.000                      307154.000                                      307154.000                                       307154.000                                      307154.000                                                          307154.000                              307154.000                     307154.000                    307154.000                             307154.000                                307154.000                        307154.000                        307154.000                          307154.000                          307154.000              307154.000      307154.000      307154.000        307154.000
mean      -0.382    359.676                 0.968                           0.032                             0.943                             0.057                     6.805         656.791                 45.360                           5.466                             2.599                712.050               54.595                         5.374                           2.818              528.392             40.863                       4.970                         2.091              840.039               59.039                         5.742                           3.324            1369.083             5.418                    1432.491                                 6088.901                                          8502.334                          0.254         0.367         0.379       0.643      0.204       0.153        1.112      0.949                 1846.008                                2681.765                               2238.911                              3219.132                      0.625           0.460             0.455              0.085                          17.668                                          15.813                                          114.113                                          95.858                                                               0.311                                 613.287                        316.262                      4089.229                               3387.648                                    21.966                             0.968                             0.032                               0.943                               0.057                   0.240           0.327           0.475             0.451
std        1.631    284.656                 0.175                           0.175                             0.232                             0.232                     2.879        1047.817                 19.494                           8.719                             4.146               1235.507               19.523                         9.325                           4.889              796.787             10.117                       7.495                         3.153             1437.931                9.984                         9.829                           5.690            2216.350             8.771                     768.930                                 1253.120                                          3997.395                          0.435         0.482         0.485       0.479      0.403       0.360        0.780      0.595                  974.242                                1138.220                               1110.800                              1207.731                      0.636           0.498             0.498              0.279                          16.452                                          12.766                                          107.755                                          90.369                                                               0.533                                 524.431                        147.739                      3623.964                               3021.219                                    34.374                             0.175                             0.175                               0.232                               0.232                   0.427           0.366           0.499             0.378
min       -1.000      1.000                 0.000                           0.000                             0.000                             0.000                     1.000           7.000                 12.500                           0.058                             0.028                 21.000               15.632                         0.158                           0.083               15.000             18.939                       0.141                         0.059               13.000               44.444                         0.089                           0.051              29.000             0.115                     150.000                                 3955.000                                          2351.000                          0.000         0.000         0.000       0.000      0.000       0.000        0.000      0.000                  595.238                                 662.202                                721.036                               839.936                      0.000           0.000             0.000              0.000                           3.000                                           2.000                                            6.000                                           1.000                                                               0.000                                   4.000                          4.000                        31.000                                 20.000                                     0.000                             0.000                             0.000                               0.000                               0.000                   0.000           0.000           0.000             0.011
25%       -1.000    111.000                 1.000                           0.000                             1.000                             0.000                     4.000          87.000                 27.586                           0.724                             0.344                189.000               34.871                         1.426                           0.748               95.000             32.759                       0.894                         0.376              195.000               51.176                         1.333                           0.772             290.000             1.148                    1064.000                                 3955.000                                          3778.000                          0.000         0.000         0.000       0.000      0.000       0.000        0.000      1.000                 1092.887                                1854.935                               1627.735                              1936.983                      0.000           0.000             0.000              0.000                           7.000                                           7.000                                           45.000                                          38.000                                                               0.000                                 353.000                        213.000                      2289.000                               1891.000                                     0.000                             1.000                             0.000                               1.000                               0.000                   0.000           0.018           0.000             0.038
50%       -1.000    291.000                 1.000                           0.000                             1.000                             0.000                     7.000         226.000                 43.135                           1.881                             0.894                210.000               56.865                         1.585                           0.831              205.000             41.667                       1.928                         0.811              288.000               56.818                         1.969                           1.140             398.000             1.575                    1411.000                                 6664.000                                         11464.000                          0.000         0.000         0.000       1.000      0.000       0.000        1.000      1.000                 1366.558                                2843.366                               1938.775                              3571.638                      1.000           0.000             0.000              0.000                          13.000                                          12.000                                           84.000                                          70.000                                                               0.000                                 536.000                        311.000                      3557.000                               2930.000                                    14.000                             1.000                             0.000                               1.000                               0.000                   0.000           0.112           0.000             0.450
75%       -1.000    578.000                 1.000                           0.000                             1.000                             0.000                     9.000         416.000                 65.129                           3.462                             1.646                557.000               72.414                         4.204                           2.204              661.000             48.824                       6.218                         2.616              708.000               67.241                         4.839                           2.802            1399.000             5.536                    1477.000                                 6974.000                                         11464.000                          1.000         1.000         1.000       1.000      0.000       0.000        2.000      1.000                 2746.212                                3460.737                               2372.176                              3939.360                      1.000           1.000             1.000              0.000                          22.000                                          20.000                                          144.000                                         120.000                                                               1.000                                 751.000                        408.000                      4973.000                               4125.000                                    35.000                             1.000                             0.000                               1.000                               0.000                   0.000           0.700           1.000             0.851
max        5.000   1000.000                 1.000                           1.000                             1.000                             1.000                    11.000        3970.000                 84.299                          33.037                            15.710               4510.000               87.500                        34.038                          17.847             2844.000             58.333                      26.752                        11.254             5228.000               80.808                        35.735                          20.689            7931.000            31.385                    2895.000                                 6974.000                                         11464.000                          1.000         1.000         1.000       1.000      1.000       1.000        2.000      2.000                 3888.445                                4529.657                               4699.074                              4869.203                      2.000           1.000             1.000              1.000                         349.000                                         209.000                                         2496.000                                        2142.000                                                              11.000                               10385.000                       1107.000                     66310.000                              55654.000                                   631.000                             1.000                             1.000                               1.000                               1.000                   1.000           0.994           1.000             0.967

In [20]:
df_jobs[['Job ID', 'Job Description', 'Job Description spacy_sentencized']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307154 entries, 0 to 307153
Data columns (total 3 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Job ID                             307154 non-null  object
 1   Job Description                    307154 non-null  object
 2   Job Description spacy_sentencized  307154 non-null  object
dtypes: object(3)
memory usage: 7.0+ MB

In [21]:
df_jobs[['Job ID', 'Job Description', 'Job Description spacy_sentencized']].head()

         Job ID                         Job Description                           Job Description spacy_sentencized
0  pj_da9f2c12243d7031  About Our Client\nThe Global KYC organisation ...                                   About Our Client
1  pj_da9f2c12243d7031  About Our Client\nThe Global KYC organisation ...  The Global KYC organisation is part of ING's C...
2  pj_da9f2c12243d7031  About Our Client\nThe Global KYC organisation ...  Its purpose is Enabling people and organisatio...
3  pj_da9f2c12243d7031  About Our Client\nThe Global KYC organisation ...  Our Global KYC organisation is a first line of...
4  pj_da9f2c12243d7031  About Our Client\nThe Global KYC organisation ...  In our Global KYC organisation you will be wor...

In [22]:
df_jobs = df_jobs.drop_duplicates(subset=['Job ID', 'Job Description', 'Job Description spacy_sentencized']).reset_index(drop=True)
df_jobs = df_jobs.dropna(subset=['Job ID', 'Job Description', 'Job Description spacy_sentencized'] + dvs_all).reset_index(drop=True)
df_jobs = df_jobs.loc[
    (df_jobs['Job Description spacy_sentencized'].progress_apply(lambda x: len(x) > 5))
    & (df_jobs['Job Description_num_words'] > 2)
    & (df_jobs['Job Description_num_chars'] > 5)
    & (df_jobs['Job Description'].progress_apply(lambda x: len(x) > 5))
    & (df_jobs['Job Description spacy_sentencized_num_words'] > 2)
    & (df_jobs['Job Description spacy_sentencized_num_chars'] > 5)
].reset_index(drop=True)

progress-bar:   0%|          | 0/307154 [00:00<?, ?it/s]

progress-bar:   0%|          | 0/307154 [00:00<?, ?it/s]

In [23]:
df_jobs['Job Description_num_words'].min()

4

In [24]:
df_jobs['Job Description_num_words'].max()

10385

In [25]:
df_jobs['Job Description spacy_sentencized_num_words'].min()

3

In [26]:
df_jobs['Job Description spacy_sentencized_num_words'].max()

349

In [27]:
df_jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307154 entries, 0 to 307153
Data columns (total 95 columns):
 #   Column                                                              Non-Null Count   Dtype
---  ------                                                              --------------   -----
 0   Search Keyword                                                      307154 non-null  object
 1   Platform                                                            307154 non-null  object
 2   Job ID                                                              307154 non-null  object
 3   Job Title                                                           307154 non-null  object
 4   Company Name                                                        307149 non-null  object
 5   Location                                                            307154 non-null  object
 6   Job Description                                                     307154 non-null  object
 7   Rating                                                              165831 non-null  float64
 8   Employment Type                                                     281052 non-null  object
 9   Company URL                                                         300561 non-null  object
 10  Job URL                                                             307154 non-null  object
 11  Job Age                                                             307154 non-null  object
 12  Job Age Number                                                      307154 non-null  object
 13  Collection Date                                                     307154 non-null  object
 14  Data Row                                                            141182 non-null  float64
 15  Tracking ID                                                         141182 non-null  object
 16  Industry                                                            167425 non-null  object
 17  Job Date                                                            141323 non-null  object
 18  Type of ownership                                                   26102 non-null   object
 19  Language                                                            307154 non-null  object
 20  Dutch Requirement in Job Ad                                         307154 non-null  object
 21  English Requirement in Job Ad                                       307154 non-null  object
 22  Dutch Requirement in Job Ad_No                                      307154 non-null  int64
 23  Dutch Requirement in Job Ad_Yes                                     307154 non-null  int64
 24  English Requirement in Job Ad_No                                    307154 non-null  int64
 25  English Requirement in Job Ad_Yes                                   307154 non-null  int64
 26  Sector Code                                                         307154 non-null  object
 27  Sector                                                              307154 non-null  object
 28  Keywords Count                                                      307154 non-null  float64
 29  Gender_Female_n                                                     307154 non-null  float64
 30  Gender_Female_% per Sector                                          307154 non-null  float64
 31  Gender_Female_% per Social Category                                 307154 non-null  float64
 32  Gender_Female_% per Workforce                                       307154 non-null  float64
 33  Gender_Male_n                                                       307154 non-null  float64
 34  Gender_Male_% per Sector                                            307154 non-null  float64
 35  Gender_Male_% per Social Category                                   307154 non-null  float64
 36  Gender_Male_% per Workforce                                         307154 non-null  float64
 37  Gender                                                              307154 non-null  object
 38  Age_Older_n                                                         307154 non-null  float64
 39  Age_Older_% per Sector                                              307154 non-null  float64
 40  Age_Older_% per Social Category                                     307154 non-null  float64
 41  Age_Older_% per Workforce                                           307154 non-null  float64
 42  Age_Younger_n                                                       307154 non-null  float64
 43  Age_Younger_% per Sector                                            307154 non-null  float64
 44  Age_Younger_% per Social Category                                   307154 non-null  float64
 45  Age_Younger_% per Workforce                                         307154 non-null  float64
 46  Age                                                                 307154 non-null  object
 47  Sector_n                                                            307154 non-null  float64
 48  % Sector per Workforce                                              307154 non-null  float64
 49  Sector Job Advertisement Count                                      307154 non-null  int64
 50  Sector Gender Designation Job Advertisement Count                   307154 non-null  int64
 51  Sector Age Designation Job Advertisement Count                      307154 non-null  int64
 52  Gender_Female                                                       307154 non-null  int64
 53  Gender_Male                                                         307154 non-null  int64
 54  Gender_Mixed                                                        307154 non-null  int64
 55  Age_Mixed                                                           307154 non-null  int64
 56  Age_Older                                                           307154 non-null  int64
 57  Age_Younger                                                         307154 non-null  int64
 58  Gender_Num                                                          307154 non-null  int64
 59  Age_Num                                                             307154 non-null  int64
 60  Interaction_Female_Older_% per Sector                               307154 non-null  float64
 61  Interaction_Female_Younger_% per Sector                             307154 non-null  float64
 62  Interaction_Male_Older_% per Sector                                 307154 non-null  float64
 63  Interaction_Male_Younger_% per Sector                               307154 non-null  float64
 64  Platform_Num                                                        307154 non-null  int64
 65  Platform_LinkedIn                                                   307154 non-null  int64
 66  Platform_Indeed                                                     307154 non-null  int64
 67  Platform_Glassdoor                                                  307154 non-null  int64
 68  Job Description spacy_sentencized                                   307154 non-null  object
 69  Job Description spacy_sentencized_num_words                         307154 non-null  int64
 70  Job Description spacy_sentencized_num_unique_words                  307154 non-null  int64
 71  Job Description spacy_sentencized_num_chars                         307154 non-null  int64
 72  Job Description spacy_sentencized_num_chars_no_whitespact_and_punt  307154 non-null  int64
 73  Job Description spacy_sentencized_num_punctuations                  307154 non-null  int64
 74  Job Description_num_words                                           307154 non-null  int64
 75  Job Description_num_unique_words                                    307154 non-null  int64
 76  Job Description_num_chars                                           307154 non-null  int64
 77  Job Description_num_chars_no_whitespact_and_punt                    307154 non-null  int64
 78  Job Description_num_punctuations                                    307154 non-null  int64
 79  Job Description spacy_sentencized_lower                             307154 non-null  object
 80  Dutch Requirement in Sentence                                       307154 non-null  category
 81  English Requirement in Sentence                                     307154 non-null  category
 82  Dutch Requirement in Sentence_No                                    307154 non-null  int64
 83  Dutch Requirement in Sentence_Yes                                   307154 non-null  int64
 84  English Requirement in Sentence_No                                  307154 non-null  int64
 85  English Requirement in Sentence_Yes                                 307154 non-null  int64
 86  Job Description spacy_tokenized                                     307154 non-null  object
 87  Job Description spacy_sentencized_cleaned                           307154 non-null  object
 88  Job Description nltk_tokenized                                      307154 non-null  object
 89  Job Description gensim_tokenized                                    307154 non-null  object
 90  Job Description bert_tokenized                                      307154 non-null  object
 91  Warmth                                                              307154 non-null  int64
 92  Warmth_Probability                                                  307154 non-null  float64
 93  Competence                                                          307154 non-null  int64
 94  Competence_Probability                                              307154 non-null  float64
dtypes: category(2), float64(27), int64(35), object(31)
memory usage: 218.5+ MB

In [28]:
df_jobs.describe()

        Rating    Data Row   Dutch Requirement in Job Ad_No  Dutch Requirement in Job Ad_Yes  English Requirement in Job Ad_No  English Requirement in Job Ad_Yes  Keywords Count  Gender_Female_n  Gender_Female_% per Sector  Gender_Female_% per Social Category  Gender_Female_% per Workforce  Gender_Male_n  Gender_Male_% per Sector  Gender_Male_% per Social Category  Gender_Male_% per Workforce  Age_Older_n  Age_Older_% per Sector  Age_Older_% per Social Category  Age_Older_% per Workforce  Age_Younger_n  Age_Younger_% per Sector  Age_Younger_% per Social Category  Age_Younger_% per Workforce  Sector_n   % Sector per Workforce  Sector Job Advertisement Count  Sector Gender Designation Job Advertisement Count  Sector Age Designation Job Advertisement Count  Gender_Female  Gender_Male  Gender_Mixed  Age_Mixed  Age_Older  Age_Younger  Gender_Num   Age_Num   Interaction_Female_Older_% per Sector  Interaction_Female_Younger_% per Sector  Interaction_Male_Older_% per Sector  Interaction_Male_Younger_% per Sector  Platform_Num  Platform_LinkedIn  Platform_Indeed  Platform_Glassdoor  Job Description spacy_sentencized_num_words  Job Description spacy_sentencized_num_unique_words  Job Description spacy_sentencized_num_chars  Job Description spacy_sentencized_num_chars_no_whitespact_and_punt  Job Description spacy_sentencized_num_punctuations  Job Description_num_words  Job Description_num_unique_words  Job Description_num_chars  Job Description_num_chars_no_whitespact_and_punt  Job Description_num_punctuations  Dutch Requirement in Sentence_No  Dutch Requirement in Sentence_Yes  English Requirement in Sentence_No  English Requirement in Sentence_Yes   Warmth    Warmth_Probability  Competence  Competence_Probability
count 165831.000 141182.000            307154.000                      307154.000                        307154.000                        307154.000                307154.000      307154.000             307154.000                      307154.000                        307154.000             307154.000           307154.000                    307154.000                      307154.000           307154.000         307154.000                  307154.000                    307154.000           307154.000           307154.000                    307154.000                      307154.000          307154.000        307154.000                  307154.000                               307154.000                                        307154.000                     307154.000    307154.000    307154.000  307154.000 307154.000  307154.000   307154.000 307154.000               307154.000                              307154.000                             307154.000                            307154.000                 307154.000      307154.000        307154.000         307154.000                      307154.000                                      307154.000                                       307154.000                                      307154.000                                                          307154.000                              307154.000                     307154.000                    307154.000                             307154.000                                307154.000                        307154.000                        307154.000                          307154.000                          307154.000              307154.000      307154.000      307154.000        307154.000
mean      -0.382    359.676                 0.968                           0.032                             0.943                             0.057                     6.805         656.791                 45.360                           5.466                             2.599                712.050               54.595                         5.374                           2.818              528.392             40.863                       4.970                         2.091              840.039               59.039                         5.742                           3.324            1369.083             5.418                    1432.491                                 6088.901                                          8502.334                          0.254         0.367         0.379       0.643      0.204       0.153        1.112      0.949                 1846.008                                2681.765                               2238.911                              3219.132                      0.625           0.460             0.455              0.085                          17.668                                          15.813                                          114.113                                          95.858                                                               0.311                                 613.287                        316.262                      4089.229                               3387.648                                    21.966                             0.968                             0.032                               0.943                               0.057                   0.240           0.327           0.475             0.451
std        1.631    284.656                 0.175                           0.175                             0.232                             0.232                     2.879        1047.817                 19.494                           8.719                             4.146               1235.507               19.523                         9.325                           4.889              796.787             10.117                       7.495                         3.153             1437.931                9.984                         9.829                           5.690            2216.350             8.771                     768.930                                 1253.120                                          3997.395                          0.435         0.482         0.485       0.479      0.403       0.360        0.780      0.595                  974.242                                1138.220                               1110.800                              1207.731                      0.636           0.498             0.498              0.279                          16.452                                          12.766                                          107.755                                          90.369                                                               0.533                                 524.431                        147.739                      3623.964                               3021.219                                    34.374                             0.175                             0.175                               0.232                               0.232                   0.427           0.366           0.499             0.378
min       -1.000      1.000                 0.000                           0.000                             0.000                             0.000                     1.000           7.000                 12.500                           0.058                             0.028                 21.000               15.632                         0.158                           0.083               15.000             18.939                       0.141                         0.059               13.000               44.444                         0.089                           0.051              29.000             0.115                     150.000                                 3955.000                                          2351.000                          0.000         0.000         0.000       0.000      0.000       0.000        0.000      0.000                  595.238                                 662.202                                721.036                               839.936                      0.000           0.000             0.000              0.000                           3.000                                           2.000                                            6.000                                           1.000                                                               0.000                                   4.000                          4.000                        31.000                                 20.000                                     0.000                             0.000                             0.000                               0.000                               0.000                   0.000           0.000           0.000             0.011
25%       -1.000    111.000                 1.000                           0.000                             1.000                             0.000                     4.000          87.000                 27.586                           0.724                             0.344                189.000               34.871                         1.426                           0.748               95.000             32.759                       0.894                         0.376              195.000               51.176                         1.333                           0.772             290.000             1.148                    1064.000                                 3955.000                                          3778.000                          0.000         0.000         0.000       0.000      0.000       0.000        0.000      1.000                 1092.887                                1854.935                               1627.735                              1936.983                      0.000           0.000             0.000              0.000                           7.000                                           7.000                                           45.000                                          38.000                                                               0.000                                 353.000                        213.000                      2289.000                               1891.000                                     0.000                             1.000                             0.000                               1.000                               0.000                   0.000           0.018           0.000             0.038
50%       -1.000    291.000                 1.000                           0.000                             1.000                             0.000                     7.000         226.000                 43.135                           1.881                             0.894                210.000               56.865                         1.585                           0.831              205.000             41.667                       1.928                         0.811              288.000               56.818                         1.969                           1.140             398.000             1.575                    1411.000                                 6664.000                                         11464.000                          0.000         0.000         0.000       1.000      0.000       0.000        1.000      1.000                 1366.558                                2843.366                               1938.775                              3571.638                      1.000           0.000             0.000              0.000                          13.000                                          12.000                                           84.000                                          70.000                                                               0.000                                 536.000                        311.000                      3557.000                               2930.000                                    14.000                             1.000                             0.000                               1.000                               0.000                   0.000           0.112           0.000             0.450
75%       -1.000    578.000                 1.000                           0.000                             1.000                             0.000                     9.000         416.000                 65.129                           3.462                             1.646                557.000               72.414                         4.204                           2.204              661.000             48.824                       6.218                         2.616              708.000               67.241                         4.839                           2.802            1399.000             5.536                    1477.000                                 6974.000                                         11464.000                          1.000         1.000         1.000       1.000      0.000       0.000        2.000      1.000                 2746.212                                3460.737                               2372.176                              3939.360                      1.000           1.000             1.000              0.000                          22.000                                          20.000                                          144.000                                         120.000                                                               1.000                                 751.000                        408.000                      4973.000                               4125.000                                    35.000                             1.000                             0.000                               1.000                               0.000                   0.000           0.700           1.000             0.851
max        5.000   1000.000                 1.000                           1.000                             1.000                             1.000                    11.000        3970.000                 84.299                          33.037                            15.710               4510.000               87.500                        34.038                          17.847             2844.000             58.333                      26.752                        11.254             5228.000               80.808                        35.735                          20.689            7931.000            31.385                    2895.000                                 6974.000                                         11464.000                          1.000         1.000         1.000       1.000      1.000       1.000        2.000      2.000                 3888.445                                4529.657                               4699.074                              4869.203                      2.000           1.000             1.000              1.000                         349.000                                         209.000                                         2496.000                                        2142.000                                                              11.000                               10385.000                       1107.000                     66310.000                              55654.000                                   631.000                             1.000                             1.000                               1.000                               1.000                   1.000           0.994           1.000             0.967

In [29]:
df_manual.head()

     Job ID           Job Description spacy_sentencized           Warmth  Competence Dutch Requirement in Sentence English Requirement in Sentence  Dutch Requirement in Sentence_No  Dutch Requirement in Sentence_Yes  English Requirement in Sentence_No  English Requirement in Sentence_Yes     Search Keyword     Platform      Job Title     Company Name  Location                    Industry                  Dutch Requirement in Job Ad English Requirement in Job Ad  Dutch Requirement in Job Ad_No  Dutch Requirement in Job Ad_Yes  English Requirement in Job Ad_No  English Requirement in Job Ad_Yes Sector Code               Sector                Keywords Count  Gender_Female_n  Gender_Female_% per Sector  Gender_Female_% per Social Category  Gender_Female_% per Workforce  Gender_Male_n  Gender_Male_% per Sector  Gender_Male_% per Social Category  Gender_Male_% per Workforce  Gender  Age_Older_n  Age_Older_% per Sector  Age_Older_% per Social Category  Age_Older_% per Workforce  Age_Younger_n  Age_Younger_% per Sector  Age_Younger_% per Social Category  Age_Younger_% per Workforce    Age      Sector_n  % Sector per Workforce  Sector Job Advertisement Count  Sector Gender Designation Job Advertisement Count  Sector Age Designation Job Advertisement Count  Gender_Female  Gender_Male  Gender_Mixed  Age_Mixed  Age_Older  Age_Younger  Gender_Num  Age_Num  Interaction_Female_Older_% per Sector  Interaction_Female_Younger_% per Sector  Interaction_Male_Older_% per Sector  Interaction_Male_Younger_% per Sector  Platform_Num  Platform_LinkedIn  Platform_Indeed  Platform_Glassdoor      Job Description spacy_sentencized_lower                Job Description spacy_tokenized               Job Description spacy_sentencized_cleaned       Job Description spacy_sentencized_num_words  Job Description spacy_sentencized_num_unique_words  Job Description spacy_sentencized_num_chars  Job Description spacy_sentencized_num_chars_no_whitespact_and_punt  Job Description spacy_sentencized_num_punctuations           Job Description nltk_tokenized                    Job Description gensim_tokenized                    Job Description bert_tokenized            Warmth_predicted  Warmth_Probability_predicted  Competence_predicted  Competence_Probability_predicted
0  3768944208  Were Happeo  a diverse team of passionate prob...     1         1                   No                             No                                1                                 0                                   1                                   0                   social work activity  Glassdoor  Inbound Marketer    Happeo     Amsterdam  Ondernemingssoftware en netwerkoplossingen              No                           No                              1                               0                                 1                                 0                       Q      Health and social work activities      11.000         1208.000                84.299                          10.052                            4.780                 224.000               15.632                        1.691                           0.886              Female   661.000             46.127                      6.218                         2.616               770.000               53.733                        5.263                           3.047              Mixed Age  1433.000          5.671                        1362                                     3955                                              11464                            1             0             0           1          0           0            0         1                   3888.445                                4529.657                               721.036                               839.936                        2               0                 0                  1          were happeo  a diverse team of passionate prob...  [were, happeo, a, diverse, team, of, passionat...  were happeo a diverse team of passionate probl...                      22                                              21                                               153                                             128                                                                  1                           [happeo, diverse, team, passionate, problem-so...  [happeo, divers, team, passion, problem, solve...  [were, ha, ##ppe, ##o, a, diverse, team, of, p...          1                    0.967                        1                        0.755
1  3768944208  Work closely with our Sales and Product leader...     1         1                   No                             No                                1                                 0                                   1                                   0                   social work activity  Glassdoor  Inbound Marketer    Happeo     Amsterdam  Ondernemingssoftware en netwerkoplossingen              No                           No                              1                               0                                 1                                 0                       Q      Health and social work activities      11.000         1208.000                84.299                          10.052                            4.780                 224.000               15.632                        1.691                           0.886              Female   661.000             46.127                      6.218                         2.616               770.000               53.733                        5.263                           3.047              Mixed Age  1433.000          5.671                        1362                                     3955                                              11464                            1             0             0           1          0           0            0         1                   3888.445                                4529.657                               721.036                               839.936                        2               0                 0                  1          work closely with our sales and product leader...  [work, closely, with, our, sales, and, product...  work closely with our sales and product leader...                      23                                              21                                               140                                             116                                                                  0                           [work, closely, sales, product, leadership, pi...  [work, close, sale, product, leadership, pinpo...  [work, closely, with, our, sales, and, product...          1                    0.917                        1                        0.914
2  3768944208  Assist Marketing & Product to position our pro...     1         1                   No                             No                                1                                 0                                   1                                   0                   social work activity  Glassdoor  Inbound Marketer    Happeo     Amsterdam  Ondernemingssoftware en netwerkoplossingen              No                           No                              1                               0                                 1                                 0                       Q      Health and social work activities      11.000         1208.000                84.299                          10.052                            4.780                 224.000               15.632                        1.691                           0.886              Female   661.000             46.127                      6.218                         2.616               770.000               53.733                        5.263                           3.047              Mixed Age  1433.000          5.671                        1362                                     3955                                              11464                            1             0             0           1          0           0            0         1                   3888.445                                4529.657                               721.036                               839.936                        2               0                 0                  1          assist marketing & product to position our pro...  [assist, marketing, product, to, position, our...  assist marketing product to position our produ...                      17                                              16                                               112                                              93                                                                  0                           [assist, marketing, product, position, product...  [assist, market, product, posit, product, impr...  [assist, marketing, &, product, to, position, ...          0                    0.419                        1                        0.895
3  3768944208  Youre not scared of a real scale-up environmen...     1         1                   No                             No                                1                                 0                                   1                                   0                   social work activity  Glassdoor  Inbound Marketer    Happeo     Amsterdam  Ondernemingssoftware en netwerkoplossingen              No                           No                              1                               0                                 1                                 0                       Q      Health and social work activities      11.000         1208.000                84.299                          10.052                            4.780                 224.000               15.632                        1.691                           0.886              Female   661.000             46.127                      6.218                         2.616               770.000               53.733                        5.263                           3.047              Mixed Age  1433.000          5.671                        1362                                     3955                                              11464                            1             0             0           1          0           0            0         1                   3888.445                                4529.657                               721.036                               839.936                        2               0                 0                  1          youre not scared of a real scale-up environmen...  [you, re, not, scared, of, a, real, scale, up,...  you re not scared of a real scale up environme...                      21                                              18                                               118                                              95                                                                  0                           [youre, scared, real, scale-up, environment, f...  [your, scare, real, scale, environ, initi, ide...  [your, ##e, not, scared, of, a, real, scale, -...          1                    0.895                        1                        0.848
4  3768944208  You will be joining a company with highly skil...     1         1                   No                             No                                1                                 0                                   1                                   0                   social work activity  Glassdoor  Inbound Marketer    Happeo     Amsterdam  Ondernemingssoftware en netwerkoplossingen              No                           No                              1                               0                                 1                                 0                       Q      Health and social work activities      11.000         1208.000                84.299                          10.052                            4.780                 224.000               15.632                        1.691                           0.886              Female   661.000             46.127                      6.218                         2.616               770.000               53.733                        5.263                           3.047              Mixed Age  1433.000          5.671                        1362                                     3955                                              11464                            1             0             0           1          0           0            0         1                   3888.445                                4529.657                               721.036                               839.936                        2               0                 0                  1          you will be joining a company with highly skil...  [you, will, be, joining, a, company, with, hig...  you will be joining a company with highly skil...                      37                                              32                                               220                                             179                                                                  2                           [joining, company, highly, skilled, smart, div...  [join, compani, highli, skill, smart, divers, ...  [you, will, be, joining, a, company, with, hig...          1                    0.953                        1                        0.791

In [30]:
df_manual.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5084 entries, 0 to 5083
Data columns (total 79 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Job ID                                                              5084 non-null   object
 1   Job Description spacy_sentencized                                   5084 non-null   object
 2   Warmth                                                              5084 non-null   int64
 3   Competence                                                          5084 non-null   int64
 4   Dutch Requirement in Sentence                                       5084 non-null   object
 5   English Requirement in Sentence                                     5084 non-null   object
 6   Dutch Requirement in Sentence_No                                    5084 non-null   int64
 7   Dutch Requirement in Sentence_Yes                                   5084 non-null   int64
 8   English Requirement in Sentence_No                                  5084 non-null   int64
 9   English Requirement in Sentence_Yes                                 5084 non-null   int64
 10  Search Keyword                                                      5084 non-null   object
 11  Platform                                                            5084 non-null   object
 12  Job Title                                                           5084 non-null   object
 13  Company Name                                                        5084 non-null   object
 14  Location                                                            5084 non-null   object
 15  Industry                                                            216 non-null    object
 16  Dutch Requirement in Job Ad                                         5084 non-null   object
 17  English Requirement in Job Ad                                       5084 non-null   object
 18  Dutch Requirement in Job Ad_No                                      5084 non-null   int64
 19  Dutch Requirement in Job Ad_Yes                                     5084 non-null   int64
 20  English Requirement in Job Ad_No                                    5084 non-null   int64
 21  English Requirement in Job Ad_Yes                                   5084 non-null   int64
 22  Sector Code                                                         5084 non-null   object
 23  Sector                                                              5084 non-null   object
 24  Keywords Count                                                      5084 non-null   float64
 25  Gender_Female_n                                                     5084 non-null   float64
 26  Gender_Female_% per Sector                                          5084 non-null   float64
 27  Gender_Female_% per Social Category                                 5084 non-null   float64
 28  Gender_Female_% per Workforce                                       5084 non-null   float64
 29  Gender_Male_n                                                       5084 non-null   float64
 30  Gender_Male_% per Sector                                            5084 non-null   float64
 31  Gender_Male_% per Social Category                                   5084 non-null   float64
 32  Gender_Male_% per Workforce                                         5084 non-null   float64
 33  Gender                                                              5084 non-null   object
 34  Age_Older_n                                                         5084 non-null   float64
 35  Age_Older_% per Sector                                              5084 non-null   float64
 36  Age_Older_% per Social Category                                     5084 non-null   float64
 37  Age_Older_% per Workforce                                           5084 non-null   float64
 38  Age_Younger_n                                                       5084 non-null   float64
 39  Age_Younger_% per Sector                                            5084 non-null   float64
 40  Age_Younger_% per Social Category                                   5084 non-null   float64
 41  Age_Younger_% per Workforce                                         5084 non-null   float64
 42  Age                                                                 5084 non-null   object
 43  Sector_n                                                            5084 non-null   float64
 44  % Sector per Workforce                                              5084 non-null   float64
 45  Sector Job Advertisement Count                                      5084 non-null   int64
 46  Sector Gender Designation Job Advertisement Count                   5084 non-null   int64
 47  Sector Age Designation Job Advertisement Count                      5084 non-null   int64
 48  Gender_Female                                                       5084 non-null   int64
 49  Gender_Male                                                         5084 non-null   int64
 50  Gender_Mixed                                                        5084 non-null   int64
 51  Age_Mixed                                                           5084 non-null   int64
 52  Age_Older                                                           5084 non-null   int64
 53  Age_Younger                                                         5084 non-null   int64
 54  Gender_Num                                                          5084 non-null   int64
 55  Age_Num                                                             5084 non-null   int64
 56  Interaction_Female_Older_% per Sector                               5084 non-null   float64
 57  Interaction_Female_Younger_% per Sector                             5084 non-null   float64
 58  Interaction_Male_Older_% per Sector                                 5084 non-null   float64
 59  Interaction_Male_Younger_% per Sector                               5084 non-null   float64
 60  Platform_Num                                                        5084 non-null   int64
 61  Platform_LinkedIn                                                   5084 non-null   int64
 62  Platform_Indeed                                                     5084 non-null   int64
 63  Platform_Glassdoor                                                  5084 non-null   int64
 64  Job Description spacy_sentencized_lower                             5084 non-null   object
 65  Job Description spacy_tokenized                                     5084 non-null   object
 66  Job Description spacy_sentencized_cleaned                           5084 non-null   object
 67  Job Description spacy_sentencized_num_words                         5084 non-null   int64
 68  Job Description spacy_sentencized_num_unique_words                  5084 non-null   int64
 69  Job Description spacy_sentencized_num_chars                         5084 non-null   int64
 70  Job Description spacy_sentencized_num_chars_no_whitespact_and_punt  5084 non-null   int64
 71  Job Description spacy_sentencized_num_punctuations                  5084 non-null   int64
 72  Job Description nltk_tokenized                                      5084 non-null   object
 73  Job Description gensim_tokenized                                    5084 non-null   object
 74  Job Description bert_tokenized                                      5084 non-null   object
 75  Warmth_predicted                                                    5084 non-null   int64
 76  Warmth_Probability_predicted                                        5084 non-null   float64
 77  Competence_predicted                                                5084 non-null   int64
 78  Competence_Probability_predicted                                    5084 non-null   float64
dtypes: float64(25), int64(32), object(22)
memory usage: 3.1+ MB

In [31]:
df_manual.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5084 entries, 0 to 5083
Data columns (total 79 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Job ID                                                              5084 non-null   object
 1   Job Description spacy_sentencized                                   5084 non-null   object
 2   Warmth                                                              5084 non-null   int64
 3   Competence                                                          5084 non-null   int64
 4   Dutch Requirement in Sentence                                       5084 non-null   object
 5   English Requirement in Sentence                                     5084 non-null   object
 6   Dutch Requirement in Sentence_No                                    5084 non-null   int64
 7   Dutch Requirement in Sentence_Yes                                   5084 non-null   int64
 8   English Requirement in Sentence_No                                  5084 non-null   int64
 9   English Requirement in Sentence_Yes                                 5084 non-null   int64
 10  Search Keyword                                                      5084 non-null   object
 11  Platform                                                            5084 non-null   object
 12  Job Title                                                           5084 non-null   object
 13  Company Name                                                        5084 non-null   object
 14  Location                                                            5084 non-null   object
 15  Industry                                                            216 non-null    object
 16  Dutch Requirement in Job Ad                                         5084 non-null   object
 17  English Requirement in Job Ad                                       5084 non-null   object
 18  Dutch Requirement in Job Ad_No                                      5084 non-null   int64
 19  Dutch Requirement in Job Ad_Yes                                     5084 non-null   int64
 20  English Requirement in Job Ad_No                                    5084 non-null   int64
 21  English Requirement in Job Ad_Yes                                   5084 non-null   int64
 22  Sector Code                                                         5084 non-null   object
 23  Sector                                                              5084 non-null   object
 24  Keywords Count                                                      5084 non-null   float64
 25  Gender_Female_n                                                     5084 non-null   float64
 26  Gender_Female_% per Sector                                          5084 non-null   float64
 27  Gender_Female_% per Social Category                                 5084 non-null   float64
 28  Gender_Female_% per Workforce                                       5084 non-null   float64
 29  Gender_Male_n                                                       5084 non-null   float64
 30  Gender_Male_% per Sector                                            5084 non-null   float64
 31  Gender_Male_% per Social Category                                   5084 non-null   float64
 32  Gender_Male_% per Workforce                                         5084 non-null   float64
 33  Gender                                                              5084 non-null   object
 34  Age_Older_n                                                         5084 non-null   float64
 35  Age_Older_% per Sector                                              5084 non-null   float64
 36  Age_Older_% per Social Category                                     5084 non-null   float64
 37  Age_Older_% per Workforce                                           5084 non-null   float64
 38  Age_Younger_n                                                       5084 non-null   float64
 39  Age_Younger_% per Sector                                            5084 non-null   float64
 40  Age_Younger_% per Social Category                                   5084 non-null   float64
 41  Age_Younger_% per Workforce                                         5084 non-null   float64
 42  Age                                                                 5084 non-null   object
 43  Sector_n                                                            5084 non-null   float64
 44  % Sector per Workforce                                              5084 non-null   float64
 45  Sector Job Advertisement Count                                      5084 non-null   int64
 46  Sector Gender Designation Job Advertisement Count                   5084 non-null   int64
 47  Sector Age Designation Job Advertisement Count                      5084 non-null   int64
 48  Gender_Female                                                       5084 non-null   int64
 49  Gender_Male                                                         5084 non-null   int64
 50  Gender_Mixed                                                        5084 non-null   int64
 51  Age_Mixed                                                           5084 non-null   int64
 52  Age_Older                                                           5084 non-null   int64
 53  Age_Younger                                                         5084 non-null   int64
 54  Gender_Num                                                          5084 non-null   int64
 55  Age_Num                                                             5084 non-null   int64
 56  Interaction_Female_Older_% per Sector                               5084 non-null   float64
 57  Interaction_Female_Younger_% per Sector                             5084 non-null   float64
 58  Interaction_Male_Older_% per Sector                                 5084 non-null   float64
 59  Interaction_Male_Younger_% per Sector                               5084 non-null   float64
 60  Platform_Num                                                        5084 non-null   int64
 61  Platform_LinkedIn                                                   5084 non-null   int64
 62  Platform_Indeed                                                     5084 non-null   int64
 63  Platform_Glassdoor                                                  5084 non-null   int64
 64  Job Description spacy_sentencized_lower                             5084 non-null   object
 65  Job Description spacy_tokenized                                     5084 non-null   object
 66  Job Description spacy_sentencized_cleaned                           5084 non-null   object
 67  Job Description spacy_sentencized_num_words                         5084 non-null   int64
 68  Job Description spacy_sentencized_num_unique_words                  5084 non-null   int64
 69  Job Description spacy_sentencized_num_chars                         5084 non-null   int64
 70  Job Description spacy_sentencized_num_chars_no_whitespact_and_punt  5084 non-null   int64
 71  Job Description spacy_sentencized_num_punctuations                  5084 non-null   int64
 72  Job Description nltk_tokenized                                      5084 non-null   object
 73  Job Description gensim_tokenized                                    5084 non-null   object
 74  Job Description bert_tokenized                                      5084 non-null   object
 75  Warmth_predicted                                                    5084 non-null   int64
 76  Warmth_Probability_predicted                                        5084 non-null   float64
 77  Competence_predicted                                                5084 non-null   int64
 78  Competence_Probability_predicted                                    5084 non-null   float64
dtypes: float64(25), int64(32), object(22)
memory usage: 3.1+ MB

In [32]:
df_manual[['Job ID', 'Job Description spacy_sentencized']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5084 entries, 0 to 5083
Data columns (total 2 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Job ID                             5084 non-null   object
 1   Job Description spacy_sentencized  5084 non-null   object
dtypes: object(2)
memory usage: 79.6+ KB

In [33]:
df_manual[['Job ID', 'Job Description spacy_sentencized']].head()

     Job ID           Job Description spacy_sentencized
0  3768944208  Were Happeo  a diverse team of passionate prob...
1  3768944208  Work closely with our Sales and Product leader...
2  3768944208  Assist Marketing & Product to position our pro...
3  3768944208  Youre not scared of a real scale-up environmen...
4  3768944208  You will be joining a company with highly skil...

In [34]:
df_manual = df_manual.drop_duplicates(subset=['Job ID', 'Job Description spacy_sentencized']).reset_index(drop=True)
df_manual = df_manual.dropna(subset=['Job ID', 'Job Description spacy_sentencized'] + dvs_all_predicted).reset_index(drop=True)
df_manual = df_manual.loc[
    (df_manual['Job Description spacy_sentencized'].progress_apply(lambda x: len(x) > 5))
    & (df_manual['Job Description spacy_sentencized_num_words'] > 2)
    & (df_manual['Job Description spacy_sentencized_num_chars'] > 5)
].reset_index(drop=True)

progress-bar:   0%|          | 0/5084 [00:00<?, ?it/s]

In [35]:
df_manual['Job Description spacy_sentencized_num_words'].min()

3

In [36]:
df_manual['Job Description spacy_sentencized_num_words'].max()

131

In [37]:
df_manual.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5084 entries, 0 to 5083
Data columns (total 79 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Job ID                                                              5084 non-null   object
 1   Job Description spacy_sentencized                                   5084 non-null   object
 2   Warmth                                                              5084 non-null   int64
 3   Competence                                                          5084 non-null   int64
 4   Dutch Requirement in Sentence                                       5084 non-null   object
 5   English Requirement in Sentence                                     5084 non-null   object
 6   Dutch Requirement in Sentence_No                                    5084 non-null   int64
 7   Dutch Requirement in Sentence_Yes                                   5084 non-null   int64
 8   English Requirement in Sentence_No                                  5084 non-null   int64
 9   English Requirement in Sentence_Yes                                 5084 non-null   int64
 10  Search Keyword                                                      5084 non-null   object
 11  Platform                                                            5084 non-null   object
 12  Job Title                                                           5084 non-null   object
 13  Company Name                                                        5084 non-null   object
 14  Location                                                            5084 non-null   object
 15  Industry                                                            216 non-null    object
 16  Dutch Requirement in Job Ad                                         5084 non-null   object
 17  English Requirement in Job Ad                                       5084 non-null   object
 18  Dutch Requirement in Job Ad_No                                      5084 non-null   int64
 19  Dutch Requirement in Job Ad_Yes                                     5084 non-null   int64
 20  English Requirement in Job Ad_No                                    5084 non-null   int64
 21  English Requirement in Job Ad_Yes                                   5084 non-null   int64
 22  Sector Code                                                         5084 non-null   object
 23  Sector                                                              5084 non-null   object
 24  Keywords Count                                                      5084 non-null   float64
 25  Gender_Female_n                                                     5084 non-null   float64
 26  Gender_Female_% per Sector                                          5084 non-null   float64
 27  Gender_Female_% per Social Category                                 5084 non-null   float64
 28  Gender_Female_% per Workforce                                       5084 non-null   float64
 29  Gender_Male_n                                                       5084 non-null   float64
 30  Gender_Male_% per Sector                                            5084 non-null   float64
 31  Gender_Male_% per Social Category                                   5084 non-null   float64
 32  Gender_Male_% per Workforce                                         5084 non-null   float64
 33  Gender                                                              5084 non-null   object
 34  Age_Older_n                                                         5084 non-null   float64
 35  Age_Older_% per Sector                                              5084 non-null   float64
 36  Age_Older_% per Social Category                                     5084 non-null   float64
 37  Age_Older_% per Workforce                                           5084 non-null   float64
 38  Age_Younger_n                                                       5084 non-null   float64
 39  Age_Younger_% per Sector                                            5084 non-null   float64
 40  Age_Younger_% per Social Category                                   5084 non-null   float64
 41  Age_Younger_% per Workforce                                         5084 non-null   float64
 42  Age                                                                 5084 non-null   object
 43  Sector_n                                                            5084 non-null   float64
 44  % Sector per Workforce                                              5084 non-null   float64
 45  Sector Job Advertisement Count                                      5084 non-null   int64
 46  Sector Gender Designation Job Advertisement Count                   5084 non-null   int64
 47  Sector Age Designation Job Advertisement Count                      5084 non-null   int64
 48  Gender_Female                                                       5084 non-null   int64
 49  Gender_Male                                                         5084 non-null   int64
 50  Gender_Mixed                                                        5084 non-null   int64
 51  Age_Mixed                                                           5084 non-null   int64
 52  Age_Older                                                           5084 non-null   int64
 53  Age_Younger                                                         5084 non-null   int64
 54  Gender_Num                                                          5084 non-null   int64
 55  Age_Num                                                             5084 non-null   int64
 56  Interaction_Female_Older_% per Sector                               5084 non-null   float64
 57  Interaction_Female_Younger_% per Sector                             5084 non-null   float64
 58  Interaction_Male_Older_% per Sector                                 5084 non-null   float64
 59  Interaction_Male_Younger_% per Sector                               5084 non-null   float64
 60  Platform_Num                                                        5084 non-null   int64
 61  Platform_LinkedIn                                                   5084 non-null   int64
 62  Platform_Indeed                                                     5084 non-null   int64
 63  Platform_Glassdoor                                                  5084 non-null   int64
 64  Job Description spacy_sentencized_lower                             5084 non-null   object
 65  Job Description spacy_tokenized                                     5084 non-null   object
 66  Job Description spacy_sentencized_cleaned                           5084 non-null   object
 67  Job Description spacy_sentencized_num_words                         5084 non-null   int64
 68  Job Description spacy_sentencized_num_unique_words                  5084 non-null   int64
 69  Job Description spacy_sentencized_num_chars                         5084 non-null   int64
 70  Job Description spacy_sentencized_num_chars_no_whitespact_and_punt  5084 non-null   int64
 71  Job Description spacy_sentencized_num_punctuations                  5084 non-null   int64
 72  Job Description nltk_tokenized                                      5084 non-null   object
 73  Job Description gensim_tokenized                                    5084 non-null   object
 74  Job Description bert_tokenized                                      5084 non-null   object
 75  Warmth_predicted                                                    5084 non-null   int64
 76  Warmth_Probability_predicted                                        5084 non-null   float64
 77  Competence_predicted                                                5084 non-null   int64
 78  Competence_Probability_predicted                                    5084 non-null   float64
dtypes: float64(25), int64(32), object(22)
memory usage: 3.1+ MB

In [38]:
df_manual.describe()

       Warmth   Competence  Dutch Requirement in Sentence_No  Dutch Requirement in Sentence_Yes  English Requirement in Sentence_No  English Requirement in Sentence_Yes  Dutch Requirement in Job Ad_No  Dutch Requirement in Job Ad_Yes  English Requirement in Job Ad_No  English Requirement in Job Ad_Yes  Keywords Count  Gender_Female_n  Gender_Female_% per Sector  Gender_Female_% per Social Category  Gender_Female_% per Workforce  Gender_Male_n  Gender_Male_% per Sector  Gender_Male_% per Social Category  Gender_Male_% per Workforce  Age_Older_n  Age_Older_% per Sector  Age_Older_% per Social Category  Age_Older_% per Workforce  Age_Younger_n  Age_Younger_% per Sector  Age_Younger_% per Social Category  Age_Younger_% per Workforce  Sector_n  % Sector per Workforce  Sector Job Advertisement Count  Sector Gender Designation Job Advertisement Count  Sector Age Designation Job Advertisement Count  Gender_Female  Gender_Male  Gender_Mixed  Age_Mixed  Age_Older  Age_Younger  Gender_Num  Age_Num  Interaction_Female_Older_% per Sector  Interaction_Female_Younger_% per Sector  Interaction_Male_Older_% per Sector  Interaction_Male_Younger_% per Sector  Platform_Num  Platform_LinkedIn  Platform_Indeed  Platform_Glassdoor  Job Description spacy_sentencized_num_words  Job Description spacy_sentencized_num_unique_words  Job Description spacy_sentencized_num_chars  Job Description spacy_sentencized_num_chars_no_whitespact_and_punt  Job Description spacy_sentencized_num_punctuations  Warmth_predicted  Warmth_Probability_predicted  Competence_predicted  Competence_Probability_predicted
count 5084.000   5084.000               5084.000                          5084.000                            5084.000                            5084.000                           5084.000                        5084.000                          5084.000                          5084.000                  5084.000        5084.000               5084.000                        5084.000                          5084.000               5084.000             5084.000                      5084.000                        5084.000             5084.000           5084.000                    5084.000                      5084.000             5084.000             5084.000                      5084.000                        5084.000            5084.000         5084.000                    5084.000                                 5084.000                                          5084.000                       5084.000      5084.000      5084.000    5084.000   5084.000    5084.000     5084.000  5084.000                5084.000                                5084.000                               5084.000                              5084.000                   5084.000        5084.000          5084.000           5084.000                        5084.000                                        5084.000                                         5084.000                                        5084.000                                                            5084.000                            5084.000                5084.000                  5084.000                    5084.000
mean     0.297      0.507                  0.999                             0.001                               0.998                               0.002                              0.967                           0.033                             0.913                             0.087                     7.163         562.727                 45.179                           4.683                             2.227                584.936               54.798                         4.415                           2.315              441.105             38.248                       4.149                         1.746              705.293               61.512                         4.821                           2.791            1147.816            4.542                    1144.567                                 6293.506                                          5737.702                          0.160         0.199         0.642       0.353      0.116       0.530        1.039     1.414                1734.330                                2773.340                               2089.613                              3376.412                      1.042           0.000             0.958              0.042                          15.045                                          13.959                                           98.920                                          82.634                                                               0.735                               0.275                   0.359                     0.515                       0.473
std      0.457      0.500                  0.034                             0.034                               0.044                               0.044                              0.179                           0.179                             0.281                             0.281                     2.401         764.539                 16.144                           6.362                             3.025                705.361               16.169                         5.323                           2.791              560.626              8.828                       5.274                         2.219              836.866                8.900                         5.720                           3.312            1370.797            5.425                     561.203                                 1026.021                                          4257.229                          0.366         0.399         0.480       0.478      0.320       0.499        0.597     0.689                 849.466                                 915.332                                908.443                              1033.093                      0.202           0.000             0.202              0.202                          10.265                                           8.583                                           69.822                                          58.272                                                               0.647                               0.447                   0.382                     0.500                       0.398
min      0.000      0.000                  0.000                             0.000                               0.000                               0.000                              0.000                           0.000                             0.000                             0.000                     2.000           7.000                 19.444                           0.058                             0.028                 21.000               15.632                         0.158                           0.083               15.000             18.939                       0.141                         0.059               13.000               44.444                         0.089                           0.051              29.000            0.115                     150.000                                 3955.000                                          2351.000                          0.000         0.000         0.000       0.000      0.000       0.000        0.000     0.000                 903.686                                 864.198                                721.036                               839.936                      1.000           0.000             0.000              0.000                           3.000                                           3.000                                            8.000                                           6.000                                                               0.000                               0.000                   0.000                     0.000                       0.011
25%      0.000      0.000                  1.000                             0.000                               1.000                               0.000                              1.000                           0.000                             1.000                             0.000                     6.000         226.000                 42.754                           1.881                             0.894                224.000               57.246                         1.691                           0.886              253.000             31.963                       2.380                         1.001              288.000               53.137                         1.969                           1.140             542.000            2.145                    1064.000                                 6664.000                                          2351.000                          0.000         0.000         0.000       0.000      0.000       0.000        1.000     1.000                1366.558                                2843.366                               1829.742                              3246.136                      1.000           0.000             1.000              0.000                           8.000                                           8.000                                           50.000                                          43.000                                                               0.000                               0.000                   0.020                     0.000                       0.030
50%      0.000      1.000                  1.000                             0.000                               1.000                               0.000                              1.000                           0.000                             1.000                             0.000                     8.000         416.000                 42.754                           3.462                             1.646                557.000               57.246                         4.204                           2.204              311.000             31.963                       2.925                         1.231              660.000               67.831                         4.511                           2.612             973.000            3.850                    1064.000                                 6664.000                                          2351.000                          0.000         0.000         1.000       0.000      0.000       1.000        1.000     2.000                1366.558                                2900.091                               1829.742                              3883.054                      1.000           0.000             1.000              0.000                          13.000                                          13.000                                           85.000                                          71.000                                                               1.000                               0.000                   0.146                     1.000                       0.600
75%      1.000      1.000                  1.000                             0.000                               1.000                               0.000                              1.000                           0.000                             1.000                             0.000                     8.000         416.000                 42.754                           3.462                             1.646                557.000               57.246                         4.204                           2.204              311.000             46.679                       2.925                         1.231              660.000               67.831                         4.511                           2.612             973.000            3.850                    1362.000                                 6664.000                                         11464.000                          0.000         0.000         1.000       1.000      0.000       1.000        1.000     2.000                1470.631                                2900.091                               1938.775                              3883.054                      1.000           0.000             1.000              0.000                          20.000                                          18.000                                          130.000                                         109.000                                                               1.000                               1.000                   0.795                     1.000                       0.875
max      1.000      1.000                  1.000                             1.000                               1.000                               1.000                              1.000                           1.000                             1.000                             1.000                    11.000        3970.000                 84.299                          33.037                            15.710               4510.000               80.556                        34.038                          17.847             2844.000             58.333                      26.752                        11.254             5228.000               80.808                        35.735                          20.689            7931.000           31.385                    2895.000                                 6974.000                                         11464.000                          1.000         1.000         1.000       1.000      1.000       1.000        2.000     2.000                3888.445                                4529.657                               4699.074                              4869.203                      2.000           0.000             1.000              1.000                         131.000                                          95.000                                          964.000                                         814.000                                                               7.000                               1.000                   0.992                     1.000                       0.966

In [39]:
assert len(df_jobs) > 0 and isinstance(df_jobs, pd.DataFrame) and all(col in df_jobs.columns for col in dvs_all), f'ERORR: LENGTH OF DF = {len(df_jobs)}'

with open(f'{data_dir}df_jobs_classified_len.txt', 'w') as f:
    f.write(str(len(df_jobs)))

df_jobs.to_pickle(f'{df_save_dir}df_jobs_classified.pkl')
df_jobs.to_csv(f'{df_save_dir}df_jobs_classified.csv', index=False)

In [40]:
with open(f'{data_dir}df_jobs_classified_len.txt', 'r') as f:
    df_jobs_len = int(f.read())

df_jobs = pd.read_pickle(f'{df_save_dir}df_jobs_classified.pkl')
assert len(df_jobs) == df_jobs_len and all(col in df_jobs.columns for col in dvs_all), f'DATAFRAME MISSING DATA! DF SHOULD BE OF LENGTH {df_jobs_len} BUT IS OF LENGTH {len(df_jobs)}'

In [41]:
assert len(df_manual) > 0 and isinstance(df_manual, pd.DataFrame) and all(col in df_manual.columns for col in dvs_all_predicted), f'ERORR: LENGTH OF DF = {len(df_manual)}'

with open(f'{data_dir}df_manual_classified_len.txt', 'w') as f:
    f.write(str(len(df_manual)))

df_manual.to_pickle(f'{df_save_dir}df_manual_classified.pkl')
df_manual.to_csv(f'{df_save_dir}df_manual_classified.csv', index=False)

In [42]:
with open(f'{data_dir}df_manual_classified_len.txt', 'r') as f:
    df_manual_len = int(f.read())

df_manual = pd.read_pickle(f'{df_save_dir}df_manual_classified.pkl')
assert len(df_manual) == df_manual_len and all(col in df_manual.columns for col in dvs_all_predicted), f'DATAFRAME MISSING DATA! DF SHOULD BE OF LENGTH {df_manual_len} BUT IS OF LENGTH {len(df_manual)}'

## Merge df_jobs with df_manual

In [43]:
merge_on_cols_list = ['Job ID', 'Job Description spacy_sentencized', 'Search Keyword', 'Platform', 'Job Title', 'Company Name', 'Location']
fill_on_cols_list = ['Job Description', 'Industry', 'Rating', 'Employment Type', 'Company URL', 'Job URL', 'Job Age', 'Job Age Number', 'Collection Date', 'Data Row', 'Tracking ID', 'Job Date', 'Type of ownership', 'Language', 'Job Description_num_words', 'Job Description_num_unique_words', 'Job Description_num_chars', 'Job Description_num_chars_no_whitespact_and_punt', 'Job Description_num_punctuations']

In [44]:
df_jobs = pd.merge(
    df_jobs,
    df_manual,
    how='outer', on=merge_on_cols_list, suffixes=('', '_actual')
).drop_duplicates(
    subset=merge_on_cols_list
).reset_index(drop=True)

In [45]:
df_jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308583 entries, 0 to 308582
Columns: 167 entries, Search Keyword to Competence_Probability_predicted
dtypes: category(2), float64(119), object(46)
memory usage: 389.0+ MB

In [46]:
df_jobs.isna().sum()

Search Keyword                                                                    0
Platform                                                                          0
Job ID                                                                            0
Job Title                                                                         0
Company Name                                                                      5
Location                                                                          0
Job Description                                                                1429
Rating                                                                       142752
Employment Type                                                               27531
Company URL                                                                    8022
Job URL                                                                        1429
Job Age                                                                        1429
Job Age Number                                                                 1429
Collection Date                                                                1429
Data Row                                                                     167401
Tracking ID                                                                  167401
Industry                                                                     141158
Job Date                                                                     167260
Type of ownership                                                            282481
Language                                                                       1429
Dutch Requirement in Job Ad                                                    1429
English Requirement in Job Ad                                                  1429
Dutch Requirement in Job Ad_No                                                 1429
Dutch Requirement in Job Ad_Yes                                                1429
English Requirement in Job Ad_No                                               1429
English Requirement in Job Ad_Yes                                              1429
Sector Code                                                                    1429
Sector                                                                         1429
Keywords Count                                                                 1429
Gender_Female_n                                                                1429
Gender_Female_% per Sector                                                     1429
Gender_Female_% per Social Category                                            1429
Gender_Female_% per Workforce                                                  1429
Gender_Male_n                                                                  1429
Gender_Male_% per Sector                                                       1429
Gender_Male_% per Social Category                                              1429
Gender_Male_% per Workforce                                                    1429
Gender                                                                         1429
Age_Older_n                                                                    1429
Age_Older_% per Sector                                                         1429
Age_Older_% per Social Category                                                1429
Age_Older_% per Workforce                                                      1429
Age_Younger_n                                                                  1429
Age_Younger_% per Sector                                                       1429
Age_Younger_% per Social Category                                              1429
Age_Younger_% per Workforce                                                    1429
Age                                                                            1429
Sector_n                                                                       1429
% Sector per Workforce                                                         1429
Sector Job Advertisement Count                                                 1429
Sector Gender Designation Job Advertisement Count                              1429
Sector Age Designation Job Advertisement Count                                 1429
Gender_Female                                                                  1429
Gender_Male                                                                    1429
Gender_Mixed                                                                   1429
Age_Mixed                                                                      1429
Age_Older                                                                      1429
Age_Younger                                                                    1429
Gender_Num                                                                     1429
Age_Num                                                                        1429
Interaction_Female_Older_% per Sector                                          1429
Interaction_Female_Younger_% per Sector                                        1429
Interaction_Male_Older_% per Sector                                            1429
Interaction_Male_Younger_% per Sector                                          1429
Platform_Num                                                                   1429
Platform_LinkedIn                                                              1429
Platform_Indeed                                                                1429
Platform_Glassdoor                                                             1429
Job Description spacy_sentencized                                                 0
Job Description spacy_sentencized_num_words                                    1429
Job Description spacy_sentencized_num_unique_words                             1429
Job Description spacy_sentencized_num_chars                                    1429
Job Description spacy_sentencized_num_chars_no_whitespact_and_punt             1429
Job Description spacy_sentencized_num_punctuations                             1429
Job Description_num_words                                                      1429
Job Description_num_unique_words                                               1429
Job Description_num_chars                                                      1429
Job Description_num_chars_no_whitespact_and_punt                               1429
Job Description_num_punctuations                                               1429
Job Description spacy_sentencized_lower                                        1429
Dutch Requirement in Sentence                                                  1429
English Requirement in Sentence                                                1429
Dutch Requirement in Sentence_No                                               1429
Dutch Requirement in Sentence_Yes                                              1429
English Requirement in Sentence_No                                             1429
English Requirement in Sentence_Yes                                            1429
Job Description spacy_tokenized                                                1429
Job Description spacy_sentencized_cleaned                                      1429
Job Description nltk_tokenized                                                 1429
Job Description gensim_tokenized                                               1429
Job Description bert_tokenized                                                 1429
Warmth                                                                         1429
Warmth_Probability                                                             1429
Competence                                                                     1429
Competence_Probability                                                         1429
Warmth_actual                                                                303499
Competence_actual                                                            303499
Dutch Requirement in Sentence_actual                                         303499
English Requirement in Sentence_actual                                       303499
Dutch Requirement in Sentence_No_actual                                      303499
Dutch Requirement in Sentence_Yes_actual                                     303499
English Requirement in Sentence_No_actual                                    303499
English Requirement in Sentence_Yes_actual                                   303499
Industry_actual                                                              308367
Dutch Requirement in Job Ad_actual                                           303499
English Requirement in Job Ad_actual                                         303499
Dutch Requirement in Job Ad_No_actual                                        303499
Dutch Requirement in Job Ad_Yes_actual                                       303499
English Requirement in Job Ad_No_actual                                      303499
English Requirement in Job Ad_Yes_actual                                     303499
Sector Code_actual                                                           303499
Sector_actual                                                                303499
Keywords Count_actual                                                        303499
Gender_Female_n_actual                                                       303499
Gender_Female_% per Sector_actual                                            303499
Gender_Female_% per Social Category_actual                                   303499
Gender_Female_% per Workforce_actual                                         303499
Gender_Male_n_actual                                                         303499
Gender_Male_% per Sector_actual                                              303499
Gender_Male_% per Social Category_actual                                     303499
Gender_Male_% per Workforce_actual                                           303499
Gender_actual                                                                303499
Age_Older_n_actual                                                           303499
Age_Older_% per Sector_actual                                                303499
Age_Older_% per Social Category_actual                                       303499
Age_Older_% per Workforce_actual                                             303499
Age_Younger_n_actual                                                         303499
Age_Younger_% per Sector_actual                                              303499
Age_Younger_% per Social Category_actual                                     303499
Age_Younger_% per Workforce_actual                                           303499
Age_actual                                                                   303499
Sector_n_actual                                                              303499
% Sector per Workforce_actual                                                303499
Sector Job Advertisement Count_actual                                        303499
Sector Gender Designation Job Advertisement Count_actual                     303499
Sector Age Designation Job Advertisement Count_actual                        303499
Gender_Female_actual                                                         303499
Gender_Male_actual                                                           303499
Gender_Mixed_actual                                                          303499
Age_Mixed_actual                                                             303499
Age_Older_actual                                                             303499
Age_Younger_actual                                                           303499
Gender_Num_actual                                                            303499
Age_Num_actual                                                               303499
Interaction_Female_Older_% per Sector_actual                                 303499
Interaction_Female_Younger_% per Sector_actual                               303499
Interaction_Male_Older_% per Sector_actual                                   303499
Interaction_Male_Younger_% per Sector_actual                                 303499
Platform_Num_actual                                                          303499
Platform_LinkedIn_actual                                                     303499
Platform_Indeed_actual                                                       303499
Platform_Glassdoor_actual                                                    303499
Job Description spacy_sentencized_lower_actual                               303499
Job Description spacy_tokenized_actual                                       303499
Job Description spacy_sentencized_cleaned_actual                             303499
Job Description spacy_sentencized_num_words_actual                           303499
Job Description spacy_sentencized_num_unique_words_actual                    303499
Job Description spacy_sentencized_num_chars_actual                           303499
Job Description spacy_sentencized_num_chars_no_whitespact_and_punt_actual    303499
Job Description spacy_sentencized_num_punctuations_actual                    303499
Job Description nltk_tokenized_actual                                        303499
Job Description gensim_tokenized_actual                                      303499
Job Description bert_tokenized_actual                                        303499
Warmth_predicted                                                             303499
Warmth_Probability_predicted                                                 303499
Competence_predicted                                                         303499
Competence_Probability_predicted                                             303499
dtype: int64

In [47]:
def fill_contradicting_cols(df_jobs):

    for col in dvs:
        fill_contradicting_dict = {
            col: f'{col}_actual',
            f'{col}_Probability': f'{col}_Probability_predicted'
        }
        for main_col, fill_col in fill_contradicting_dict.items():
            print(f'Filling {main_col} with values from {fill_col}')
            df_jobs[main_col] = df_jobs[main_col].fillna(df_jobs[fill_col])
            mask = (
                (df_jobs[main_col] != df_jobs[fill_col])
                & (~df_jobs[fill_col].isna())
                | (df_jobs[main_col].isna())
            )
            df_jobs.loc[mask, main_col] = df_jobs.loc[mask, fill_col]
            assert df_jobs[main_col].isna().sum() == 0, f'Missing values found in {main_col} column'

    return df_jobs

In [48]:
df_jobs[
    [
        'Warmth', 'Warmth_Probability', 'Warmth_actual', 'Warmth_predicted', 'Warmth_Probability_predicted',
        'Competence', 'Competence_Probability', 'Competence_actual', 'Competence_predicted', 'Competence_Probability_predicted'
    ]
].head()

   Warmth  Warmth_Probability  Warmth_actual  Warmth_predicted  Warmth_Probability_predicted  Competence  Competence_Probability  Competence_actual  Competence_predicted  Competence_Probability_predicted
0  0.000         0.012             NaN              NaN                     NaN                 0.000             0.015                 NaN                  NaN                         NaN
1  0.000         0.014             NaN              NaN                     NaN                 0.000             0.059                 NaN                  NaN                         NaN
2  0.000         0.291             NaN              NaN                     NaN                 1.000             0.637                 NaN                  NaN                         NaN
3  0.000         0.163             NaN              NaN                     NaN                 1.000             0.924                 NaN                  NaN                         NaN
4  1.000         0.851             NaN              NaN                     NaN                 0.000             0.062                 NaN                  NaN                         NaN

In [49]:
df_jobs[
    [
        'Warmth', 'Warmth_Probability', 'Warmth_actual', 'Warmth_predicted', 'Warmth_Probability_predicted',
        'Competence', 'Competence_Probability', 'Competence_actual', 'Competence_predicted', 'Competence_Probability_predicted'
    ]
].tail()

        Warmth  Warmth_Probability  Warmth_actual  Warmth_predicted  Warmth_Probability_predicted  Competence  Competence_Probability  Competence_actual  Competence_predicted  Competence_Probability_predicted
308578   NaN           NaN             0.000            0.000                   0.077                 NaN               NaN                 0.000                0.000                       0.020
308579   NaN           NaN             0.000            0.000                   0.030                 NaN               NaN                 0.000                0.000                       0.021
308580   NaN           NaN             0.000            0.000                   0.004                 NaN               NaN                 0.000                0.000                       0.014
308581   NaN           NaN             0.000            0.000                   0.041                 NaN               NaN                 0.000                0.000                       0.013
308582   NaN           NaN             0.000            0.000                   0.003                 NaN               NaN                 0.000                0.000                       0.013

In [50]:
df_jobs = fill_contradicting_cols(df_jobs)

Filling Warmth with values from Warmth_actual
Filling Warmth_Probability with values from Warmth_Probability_predicted
Filling Competence with values from Competence_actual
Filling Competence_Probability with values from Competence_Probability_predicted

In [51]:
df_jobs[
    [
        'Warmth', 'Warmth_Probability', 'Warmth_actual', 'Warmth_predicted', 'Warmth_Probability_predicted',
        'Competence', 'Competence_Probability', 'Competence_actual', 'Competence_predicted', 'Competence_Probability_predicted'
    ]
].head()

   Warmth  Warmth_Probability  Warmth_actual  Warmth_predicted  Warmth_Probability_predicted  Competence  Competence_Probability  Competence_actual  Competence_predicted  Competence_Probability_predicted
0  0.000         0.012             NaN              NaN                     NaN                 0.000             0.015                 NaN                  NaN                         NaN
1  0.000         0.014             NaN              NaN                     NaN                 0.000             0.059                 NaN                  NaN                         NaN
2  0.000         0.291             NaN              NaN                     NaN                 1.000             0.637                 NaN                  NaN                         NaN
3  0.000         0.163             NaN              NaN                     NaN                 1.000             0.924                 NaN                  NaN                         NaN
4  1.000         0.851             NaN              NaN                     NaN                 0.000             0.062                 NaN                  NaN                         NaN

In [52]:
df_jobs[
    [
        'Warmth', 'Warmth_Probability', 'Warmth_actual', 'Warmth_predicted', 'Warmth_Probability_predicted',
        'Competence', 'Competence_Probability', 'Competence_actual', 'Competence_predicted', 'Competence_Probability_predicted'
    ]
].tail()

        Warmth  Warmth_Probability  Warmth_actual  Warmth_predicted  Warmth_Probability_predicted  Competence  Competence_Probability  Competence_actual  Competence_predicted  Competence_Probability_predicted
308578  0.000         0.077            0.000            0.000                   0.077                0.000             0.020                0.000                0.000                       0.020
308579  0.000         0.030            0.000            0.000                   0.030                0.000             0.021                0.000                0.000                       0.021
308580  0.000         0.004            0.000            0.000                   0.004                0.000             0.014                0.000                0.000                       0.014
308581  0.000         0.041            0.000            0.000                   0.041                0.000             0.013                0.000                0.000                       0.013
308582  0.000         0.003            0.000            0.000                   0.003                0.000             0.013                0.000                0.000                       0.013

In [53]:
# Fill in other nan values from columns with '_actual' suffix from df_manual
for col in df_jobs.columns:
    if '_actual' not in col\
        and '_predicted' not in col\
            and '_Probability' not in col\
                and col not in dvs\
                    and col not in merge_on_cols_list + fill_on_cols_list\
                        and df_jobs[col].isna().sum() != 0:
                        df_jobs[col] = df_jobs[col].fillna(df_jobs[f'{col}_actual'])

In [54]:
df_jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308583 entries, 0 to 308582
Columns: 167 entries, Search Keyword to Competence_Probability_predicted
dtypes: category(2), float64(119), object(46)
memory usage: 389.0+ MB

In [55]:
df_jobs.isna().sum()

Search Keyword                                                                    0
Platform                                                                          0
Job ID                                                                            0
Job Title                                                                         0
Company Name                                                                      5
Location                                                                          0
Job Description                                                                1429
Rating                                                                       142752
Employment Type                                                               27531
Company URL                                                                    8022
Job URL                                                                        1429
Job Age                                                                        1429
Job Age Number                                                                 1429
Collection Date                                                                1429
Data Row                                                                     167401
Tracking ID                                                                  167401
Industry                                                                     141158
Job Date                                                                     167260
Type of ownership                                                            282481
Language                                                                       1429
Dutch Requirement in Job Ad                                                       0
English Requirement in Job Ad                                                     0
Dutch Requirement in Job Ad_No                                                    0
Dutch Requirement in Job Ad_Yes                                                   0
English Requirement in Job Ad_No                                                  0
English Requirement in Job Ad_Yes                                                 0
Sector Code                                                                       0
Sector                                                                            0
Keywords Count                                                                    0
Gender_Female_n                                                                   0
Gender_Female_% per Sector                                                        0
Gender_Female_% per Social Category                                               0
Gender_Female_% per Workforce                                                     0
Gender_Male_n                                                                     0
Gender_Male_% per Sector                                                          0
Gender_Male_% per Social Category                                                 0
Gender_Male_% per Workforce                                                       0
Gender                                                                            0
Age_Older_n                                                                       0
Age_Older_% per Sector                                                            0
Age_Older_% per Social Category                                                   0
Age_Older_% per Workforce                                                         0
Age_Younger_n                                                                     0
Age_Younger_% per Sector                                                          0
Age_Younger_% per Social Category                                                 0
Age_Younger_% per Workforce                                                       0
Age                                                                               0
Sector_n                                                                          0
% Sector per Workforce                                                            0
Sector Job Advertisement Count                                                    0
Sector Gender Designation Job Advertisement Count                                 0
Sector Age Designation Job Advertisement Count                                    0
Gender_Female                                                                     0
Gender_Male                                                                       0
Gender_Mixed                                                                      0
Age_Mixed                                                                         0
Age_Older                                                                         0
Age_Younger                                                                       0
Gender_Num                                                                        0
Age_Num                                                                           0
Interaction_Female_Older_% per Sector                                             0
Interaction_Female_Younger_% per Sector                                           0
Interaction_Male_Older_% per Sector                                               0
Interaction_Male_Younger_% per Sector                                             0
Platform_Num                                                                      0
Platform_LinkedIn                                                                 0
Platform_Indeed                                                                   0
Platform_Glassdoor                                                                0
Job Description spacy_sentencized                                                 0
Job Description spacy_sentencized_num_words                                       0
Job Description spacy_sentencized_num_unique_words                                0
Job Description spacy_sentencized_num_chars                                       0
Job Description spacy_sentencized_num_chars_no_whitespact_and_punt                0
Job Description spacy_sentencized_num_punctuations                                0
Job Description_num_words                                                      1429
Job Description_num_unique_words                                               1429
Job Description_num_chars                                                      1429
Job Description_num_chars_no_whitespact_and_punt                               1429
Job Description_num_punctuations                                               1429
Job Description spacy_sentencized_lower                                           0
Dutch Requirement in Sentence                                                     0
English Requirement in Sentence                                                   0
Dutch Requirement in Sentence_No                                                  0
Dutch Requirement in Sentence_Yes                                                 0
English Requirement in Sentence_No                                                0
English Requirement in Sentence_Yes                                               0
Job Description spacy_tokenized                                                   0
Job Description spacy_sentencized_cleaned                                         0
Job Description nltk_tokenized                                                    0
Job Description gensim_tokenized                                                  0
Job Description bert_tokenized                                                    0
Warmth                                                                            0
Warmth_Probability                                                                0
Competence                                                                        0
Competence_Probability                                                            0
Warmth_actual                                                                303499
Competence_actual                                                            303499
Dutch Requirement in Sentence_actual                                         303499
English Requirement in Sentence_actual                                       303499
Dutch Requirement in Sentence_No_actual                                      303499
Dutch Requirement in Sentence_Yes_actual                                     303499
English Requirement in Sentence_No_actual                                    303499
English Requirement in Sentence_Yes_actual                                   303499
Industry_actual                                                              308367
Dutch Requirement in Job Ad_actual                                           303499
English Requirement in Job Ad_actual                                         303499
Dutch Requirement in Job Ad_No_actual                                        303499
Dutch Requirement in Job Ad_Yes_actual                                       303499
English Requirement in Job Ad_No_actual                                      303499
English Requirement in Job Ad_Yes_actual                                     303499
Sector Code_actual                                                           303499
Sector_actual                                                                303499
Keywords Count_actual                                                        303499
Gender_Female_n_actual                                                       303499
Gender_Female_% per Sector_actual                                            303499
Gender_Female_% per Social Category_actual                                   303499
Gender_Female_% per Workforce_actual                                         303499
Gender_Male_n_actual                                                         303499
Gender_Male_% per Sector_actual                                              303499
Gender_Male_% per Social Category_actual                                     303499
Gender_Male_% per Workforce_actual                                           303499
Gender_actual                                                                303499
Age_Older_n_actual                                                           303499
Age_Older_% per Sector_actual                                                303499
Age_Older_% per Social Category_actual                                       303499
Age_Older_% per Workforce_actual                                             303499
Age_Younger_n_actual                                                         303499
Age_Younger_% per Sector_actual                                              303499
Age_Younger_% per Social Category_actual                                     303499
Age_Younger_% per Workforce_actual                                           303499
Age_actual                                                                   303499
Sector_n_actual                                                              303499
% Sector per Workforce_actual                                                303499
Sector Job Advertisement Count_actual                                        303499
Sector Gender Designation Job Advertisement Count_actual                     303499
Sector Age Designation Job Advertisement Count_actual                        303499
Gender_Female_actual                                                         303499
Gender_Male_actual                                                           303499
Gender_Mixed_actual                                                          303499
Age_Mixed_actual                                                             303499
Age_Older_actual                                                             303499
Age_Younger_actual                                                           303499
Gender_Num_actual                                                            303499
Age_Num_actual                                                               303499
Interaction_Female_Older_% per Sector_actual                                 303499
Interaction_Female_Younger_% per Sector_actual                               303499
Interaction_Male_Older_% per Sector_actual                                   303499
Interaction_Male_Younger_% per Sector_actual                                 303499
Platform_Num_actual                                                          303499
Platform_LinkedIn_actual                                                     303499
Platform_Indeed_actual                                                       303499
Platform_Glassdoor_actual                                                    303499
Job Description spacy_sentencized_lower_actual                               303499
Job Description spacy_tokenized_actual                                       303499
Job Description spacy_sentencized_cleaned_actual                             303499
Job Description spacy_sentencized_num_words_actual                           303499
Job Description spacy_sentencized_num_unique_words_actual                    303499
Job Description spacy_sentencized_num_chars_actual                           303499
Job Description spacy_sentencized_num_chars_no_whitespact_and_punt_actual    303499
Job Description spacy_sentencized_num_punctuations_actual                    303499
Job Description nltk_tokenized_actual                                        303499
Job Description gensim_tokenized_actual                                      303499
Job Description bert_tokenized_actual                                        303499
Warmth_predicted                                                             303499
Warmth_Probability_predicted                                                 303499
Competence_predicted                                                         303499
Competence_Probability_predicted                                             303499
dtype: int64

In [56]:
df_jobs = df_jobs.drop(
    columns=
    [
        col
        for col in df_jobs.columns
        if '_actual' in col
        and col not in ['Warmth_actual', 'Competence_actual']
    ]
).reset_index(drop=True)

In [57]:
df_jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308583 entries, 0 to 308582
Columns: 101 entries, Search Keyword to Competence_Probability_predicted
dtypes: category(2), float64(68), object(31)
memory usage: 233.7+ MB

In [58]:
df_jobs.isna().sum()

Search Keyword                                                             0
Platform                                                                   0
Job ID                                                                     0
Job Title                                                                  0
Company Name                                                               5
Location                                                                   0
Job Description                                                         1429
Rating                                                                142752
Employment Type                                                        27531
Company URL                                                             8022
Job URL                                                                 1429
Job Age                                                                 1429
Job Age Number                                                          1429
Collection Date                                                         1429
Data Row                                                              167401
Tracking ID                                                           167401
Industry                                                              141158
Job Date                                                              167260
Type of ownership                                                     282481
Language                                                                1429
Dutch Requirement in Job Ad                                                0
English Requirement in Job Ad                                              0
Dutch Requirement in Job Ad_No                                             0
Dutch Requirement in Job Ad_Yes                                            0
English Requirement in Job Ad_No                                           0
English Requirement in Job Ad_Yes                                          0
Sector Code                                                                0
Sector                                                                     0
Keywords Count                                                             0
Gender_Female_n                                                            0
Gender_Female_% per Sector                                                 0
Gender_Female_% per Social Category                                        0
Gender_Female_% per Workforce                                              0
Gender_Male_n                                                              0
Gender_Male_% per Sector                                                   0
Gender_Male_% per Social Category                                          0
Gender_Male_% per Workforce                                                0
Gender                                                                     0
Age_Older_n                                                                0
Age_Older_% per Sector                                                     0
Age_Older_% per Social Category                                            0
Age_Older_% per Workforce                                                  0
Age_Younger_n                                                              0
Age_Younger_% per Sector                                                   0
Age_Younger_% per Social Category                                          0
Age_Younger_% per Workforce                                                0
Age                                                                        0
Sector_n                                                                   0
% Sector per Workforce                                                     0
Sector Job Advertisement Count                                             0
Sector Gender Designation Job Advertisement Count                          0
Sector Age Designation Job Advertisement Count                             0
Gender_Female                                                              0
Gender_Male                                                                0
Gender_Mixed                                                               0
Age_Mixed                                                                  0
Age_Older                                                                  0
Age_Younger                                                                0
Gender_Num                                                                 0
Age_Num                                                                    0
Interaction_Female_Older_% per Sector                                      0
Interaction_Female_Younger_% per Sector                                    0
Interaction_Male_Older_% per Sector                                        0
Interaction_Male_Younger_% per Sector                                      0
Platform_Num                                                               0
Platform_LinkedIn                                                          0
Platform_Indeed                                                            0
Platform_Glassdoor                                                         0
Job Description spacy_sentencized                                          0
Job Description spacy_sentencized_num_words                                0
Job Description spacy_sentencized_num_unique_words                         0
Job Description spacy_sentencized_num_chars                                0
Job Description spacy_sentencized_num_chars_no_whitespact_and_punt         0
Job Description spacy_sentencized_num_punctuations                         0
Job Description_num_words                                               1429
Job Description_num_unique_words                                        1429
Job Description_num_chars                                               1429
Job Description_num_chars_no_whitespact_and_punt                        1429
Job Description_num_punctuations                                        1429
Job Description spacy_sentencized_lower                                    0
Dutch Requirement in Sentence                                              0
English Requirement in Sentence                                            0
Dutch Requirement in Sentence_No                                           0
Dutch Requirement in Sentence_Yes                                          0
English Requirement in Sentence_No                                         0
English Requirement in Sentence_Yes                                        0
Job Description spacy_tokenized                                            0
Job Description spacy_sentencized_cleaned                                  0
Job Description nltk_tokenized                                             0
Job Description gensim_tokenized                                           0
Job Description bert_tokenized                                             0
Warmth                                                                     0
Warmth_Probability                                                         0
Competence                                                                 0
Competence_Probability                                                     0
Warmth_actual                                                         303499
Competence_actual                                                     303499
Warmth_predicted                                                      303499
Warmth_Probability_predicted                                          303499
Competence_predicted                                                  303499
Competence_Probability_predicted                                      303499
dtype: int64

## Clean df_jobs

In [59]:
%%time
# Conver Job ID and Sentence to str
str_cols = [
    'Job ID',
    'Job Description spacy_sentencized',
]

for col in str_cols:
    df_jobs[col] = df_jobs[col].astype(str, errors='ignore').progress_apply(lambda x: x.strip().replace('[', '').replace(']', ''))
    df_jobs[col] = df_jobs[col].progress_apply(lambda x: x.strip())
    df_jobs[col] = df_jobs[col].progress_apply(lambda x: unicodedata.normalize('NFKD', x.encode('ascii', 'ignore').decode('utf-8', 'ignore')))
    print(f'{col} converted to str.' if all(df_jobs[col].progress_apply(lambda x: isinstance(x, str))) else f'{col} NOT converted to str.')

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

Job ID converted to str.

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

Job Description spacy_sentencized converted to str.
CPU times: user 2.09 s, sys: 103 ms, total: 2.19 s
Wall time: 2.78 s

In [60]:
# Convert Warmth and Competence to int
# Warmth 1 = 1741, Competence 1 = 3043
int_cols = [
    'Warmth',
    'Competence',
    'Warmth_actual',
    'Competence_actual',
    'Warmth_predicted',
    'Competence_predicted',
]

for col in int_cols:
    df_jobs[col] = df_jobs[col].astype(np.int64, errors='ignore')
    print(f'{col} converted to int.' if all(df_jobs[col].progress_apply(lambda x: isinstance(x, int))) else f'{col} NOT converted to int.')
    print(f'{col} value counts:\n{df_jobs[col].value_counts()}')

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

Warmth converted to int.
Warmth value counts:
Warmth
0    234366
1     74217
Name: count, dtype: int64

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

Competence converted to int.
Competence value counts:
Competence
0    161987
1    146596
Name: count, dtype: int64

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

Warmth_actual NOT converted to int.
Warmth_actual value counts:
Warmth_actual
0.000    3574
1.000    1510
Name: count, dtype: int64

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

Competence_actual NOT converted to int.
Competence_actual value counts:
Competence_actual
1.000    2576
0.000    2508
Name: count, dtype: int64

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

Warmth_predicted NOT converted to int.
Warmth_predicted value counts:
Warmth_predicted
0.000    3684
1.000    1400
Name: count, dtype: int64

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

Competence_predicted NOT converted to int.
Competence_predicted value counts:
Competence_predicted
1.000    2618
0.000    2466
Name: count, dtype: int64

In [61]:
# Convert Warmth_Probability and Competence_Probability to float
# Warmth 1 = 1741, Competence 1 = 3043
float_cols = [
    'Warmth_Probability',
    'Competence_Probability',
    'Warmth_Probability_predicted',
    'Competence_Probability_predicted',
]

for col in float_cols:
    df_jobs[col] = df_jobs[col].astype(np.float64, errors='ignore')
    print(f'{col} converted to float.' if all(df_jobs[col].progress_apply(lambda x: isinstance(x, float))) else f'{col} NOT converted to int.')

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

Warmth_Probability converted to float.

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

Competence_Probability converted to float.

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

Warmth_Probability_predicted converted to float.

progress-bar:   0%|          | 0/308583 [00:00<?, ?it/s]

Competence_Probability_predicted converted to float.

In [62]:
df_jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308583 entries, 0 to 308582
Columns: 101 entries, Search Keyword to Competence_Probability_predicted
dtypes: category(2), float64(66), int64(2), object(31)
memory usage: 233.7+ MB

In [63]:
df_jobs = df_jobs.dropna(
    subset=[
        col
        for col in df_jobs.columns
        if '_actual' not in col
        and '_predicted' not in col
        and col not in merge_on_cols_list + fill_on_cols_list
    ]
)

In [64]:
df_jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308583 entries, 0 to 308582
Columns: 101 entries, Search Keyword to Competence_Probability_predicted
dtypes: category(2), float64(66), int64(2), object(31)
memory usage: 233.7+ MB

In [65]:
df_jobs = df_jobs.drop_duplicates(subset=merge_on_cols_list + fill_on_cols_list)

In [66]:
df_jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308583 entries, 0 to 308582
Columns: 101 entries, Search Keyword to Competence_Probability_predicted
dtypes: category(2), float64(66), int64(2), object(31)
memory usage: 233.7+ MB

In [67]:
df_jobs.isna().sum()

Search Keyword                                                             0
Platform                                                                   0
Job ID                                                                     0
Job Title                                                                  0
Company Name                                                               5
Location                                                                   0
Job Description                                                         1429
Rating                                                                142752
Employment Type                                                        27531
Company URL                                                             8022
Job URL                                                                 1429
Job Age                                                                 1429
Job Age Number                                                          1429
Collection Date                                                         1429
Data Row                                                              167401
Tracking ID                                                           167401
Industry                                                              141158
Job Date                                                              167260
Type of ownership                                                     282481
Language                                                                1429
Dutch Requirement in Job Ad                                                0
English Requirement in Job Ad                                              0
Dutch Requirement in Job Ad_No                                             0
Dutch Requirement in Job Ad_Yes                                            0
English Requirement in Job Ad_No                                           0
English Requirement in Job Ad_Yes                                          0
Sector Code                                                                0
Sector                                                                     0
Keywords Count                                                             0
Gender_Female_n                                                            0
Gender_Female_% per Sector                                                 0
Gender_Female_% per Social Category                                        0
Gender_Female_% per Workforce                                              0
Gender_Male_n                                                              0
Gender_Male_% per Sector                                                   0
Gender_Male_% per Social Category                                          0
Gender_Male_% per Workforce                                                0
Gender                                                                     0
Age_Older_n                                                                0
Age_Older_% per Sector                                                     0
Age_Older_% per Social Category                                            0
Age_Older_% per Workforce                                                  0
Age_Younger_n                                                              0
Age_Younger_% per Sector                                                   0
Age_Younger_% per Social Category                                          0
Age_Younger_% per Workforce                                                0
Age                                                                        0
Sector_n                                                                   0
% Sector per Workforce                                                     0
Sector Job Advertisement Count                                             0
Sector Gender Designation Job Advertisement Count                          0
Sector Age Designation Job Advertisement Count                             0
Gender_Female                                                              0
Gender_Male                                                                0
Gender_Mixed                                                               0
Age_Mixed                                                                  0
Age_Older                                                                  0
Age_Younger                                                                0
Gender_Num                                                                 0
Age_Num                                                                    0
Interaction_Female_Older_% per Sector                                      0
Interaction_Female_Younger_% per Sector                                    0
Interaction_Male_Older_% per Sector                                        0
Interaction_Male_Younger_% per Sector                                      0
Platform_Num                                                               0
Platform_LinkedIn                                                          0
Platform_Indeed                                                            0
Platform_Glassdoor                                                         0
Job Description spacy_sentencized                                          0
Job Description spacy_sentencized_num_words                                0
Job Description spacy_sentencized_num_unique_words                         0
Job Description spacy_sentencized_num_chars                                0
Job Description spacy_sentencized_num_chars_no_whitespact_and_punt         0
Job Description spacy_sentencized_num_punctuations                         0
Job Description_num_words                                               1429
Job Description_num_unique_words                                        1429
Job Description_num_chars                                               1429
Job Description_num_chars_no_whitespact_and_punt                        1429
Job Description_num_punctuations                                        1429
Job Description spacy_sentencized_lower                                    0
Dutch Requirement in Sentence                                              0
English Requirement in Sentence                                            0
Dutch Requirement in Sentence_No                                           0
Dutch Requirement in Sentence_Yes                                          0
English Requirement in Sentence_No                                         0
English Requirement in Sentence_Yes                                        0
Job Description spacy_tokenized                                            0
Job Description spacy_sentencized_cleaned                                  0
Job Description nltk_tokenized                                             0
Job Description gensim_tokenized                                           0
Job Description bert_tokenized                                             0
Warmth                                                                     0
Warmth_Probability                                                         0
Competence                                                                 0
Competence_Probability                                                     0
Warmth_actual                                                         303499
Competence_actual                                                     303499
Warmth_predicted                                                      303499
Warmth_Probability_predicted                                          303499
Competence_predicted                                                  303499
Competence_Probability_predicted                                      303499
dtype: int64

In [68]:
df_jobs.describe()

        Rating    Data Row   Dutch Requirement in Job Ad_No  Dutch Requirement in Job Ad_Yes  English Requirement in Job Ad_No  English Requirement in Job Ad_Yes  Keywords Count  Gender_Female_n  Gender_Female_% per Sector  Gender_Female_% per Social Category  Gender_Female_% per Workforce  Gender_Male_n  Gender_Male_% per Sector  Gender_Male_% per Social Category  Gender_Male_% per Workforce  Age_Older_n  Age_Older_% per Sector  Age_Older_% per Social Category  Age_Older_% per Workforce  Age_Younger_n  Age_Younger_% per Sector  Age_Younger_% per Social Category  Age_Younger_% per Workforce  Sector_n   % Sector per Workforce  Sector Job Advertisement Count  Sector Gender Designation Job Advertisement Count  Sector Age Designation Job Advertisement Count  Gender_Female  Gender_Male  Gender_Mixed  Age_Mixed  Age_Older  Age_Younger  Gender_Num   Age_Num   Interaction_Female_Older_% per Sector  Interaction_Female_Younger_% per Sector  Interaction_Male_Older_% per Sector  Interaction_Male_Younger_% per Sector  Platform_Num  Platform_LinkedIn  Platform_Indeed  Platform_Glassdoor  Job Description spacy_sentencized_num_words  Job Description spacy_sentencized_num_unique_words  Job Description spacy_sentencized_num_chars  Job Description spacy_sentencized_num_chars_no_whitespact_and_punt  Job Description spacy_sentencized_num_punctuations  Job Description_num_words  Job Description_num_unique_words  Job Description_num_chars  Job Description_num_chars_no_whitespact_and_punt  Job Description_num_punctuations  Dutch Requirement in Sentence_No  Dutch Requirement in Sentence_Yes  English Requirement in Sentence_No  English Requirement in Sentence_Yes   Warmth    Warmth_Probability  Competence  Competence_Probability  Warmth_actual  Competence_actual  Warmth_predicted  Warmth_Probability_predicted  Competence_predicted  Competence_Probability_predicted
count 165831.000 141182.000            308583.000                      308583.000                        308583.000                        308583.000                308583.000      308583.000             308583.000                      308583.000                        308583.000             308583.000           308583.000                    308583.000                      308583.000           308583.000         308583.000                  308583.000                    308583.000           308583.000           308583.000                    308583.000                      308583.000          308583.000        308583.000                  308583.000                               308583.000                                        308583.000                     308583.000    308583.000    308583.000  308583.000 308583.000  308583.000   308583.000 308583.000               308583.000                              308583.000                             308583.000                            308583.000                 308583.000      308583.000        308583.000         308583.000                      308583.000                                      308583.000                                       308583.000                                      308583.000                                                          308583.000                              307154.000                     307154.000                    307154.000                             307154.000                                307154.000                        308583.000                        308583.000                          308583.000                          308583.000              308583.000      308583.000      308583.000        308583.000          5084.000         5084.000           5084.000                5084.000                  5084.000                    5084.000
mean      -0.382    359.676                 0.969                           0.031                             0.943                             0.057                     6.807         656.504                 45.363                           5.463                             2.598                711.436               54.592                         5.369                           2.815              528.040             40.850                       4.967                         2.090              839.487               59.052                         5.738                           3.322            1368.182             5.414                    1431.146                                 6089.717                                          8489.368                          0.254         0.366         0.380       0.642      0.204       0.155        1.112      0.951                 1845.628                                2682.441                               2237.954                              3219.732                      0.627           0.458             0.457              0.085                          17.664                                          15.811                                          114.108                                          95.849                                                               0.313                                 613.287                        316.262                      4089.229                               3387.648                                    21.966                             0.969                             0.031                               0.943                               0.057                   0.241           0.327           0.475             0.451             0.297            0.507              0.275                   0.359                     0.515                       0.473
std        1.631    284.656                 0.175                           0.175                             0.232                             0.232                     2.877        1046.885                 19.480                           8.712                             4.143               1233.633               19.509                         9.310                           4.882              795.992             10.114                       7.487                         3.150             1435.825                9.981                         9.814                           5.682            2213.400             8.759                     768.401                                 1252.281                                          4003.115                          0.435         0.482         0.485       0.480      0.403       0.362        0.779      0.597                  973.828                                1137.288                               1109.907                              1207.147                      0.635           0.498             0.498              0.279                          16.437                                          12.756                                          107.676                                          90.302                                                               0.536                                 524.431                        147.739                      3623.964                               3021.219                                    34.374                             0.174                             0.174                               0.231                               0.231                   0.427           0.366           0.499             0.378             0.457            0.500              0.447                   0.382                     0.500                       0.398
min       -1.000      1.000                 0.000                           0.000                             0.000                             0.000                     1.000           7.000                 12.500                           0.058                             0.028                 21.000               15.632                         0.158                           0.083               15.000             18.939                       0.141                         0.059               13.000               44.444                         0.089                           0.051              29.000             0.115                     150.000                                 3955.000                                          2351.000                          0.000         0.000         0.000       0.000      0.000       0.000        0.000      0.000                  595.238                                 662.202                                721.036                               839.936                      0.000           0.000             0.000              0.000                           3.000                                           2.000                                            6.000                                           1.000                                                               0.000                                   4.000                          4.000                        31.000                                 20.000                                     0.000                             0.000                             0.000                               0.000                               0.000                   0.000           0.000           0.000             0.011             0.000            0.000              0.000                   0.000                     0.000                       0.011
25%       -1.000    111.000                 1.000                           0.000                             1.000                             0.000                     4.000          87.000                 27.586                           0.724                             0.344                189.000               34.871                         1.426                           0.748               95.000             32.759                       0.894                         0.376              195.000               51.176                         1.333                           0.772             290.000             1.148                    1064.000                                 3955.000                                          3778.000                          0.000         0.000         0.000       0.000      0.000       0.000        0.000      1.000                 1092.887                                1854.935                               1627.735                              1936.983                      0.000           0.000             0.000              0.000                           7.000                                           7.000                                           45.000                                          38.000                                                               0.000                                 353.000                        213.000                      2289.000                               1891.000                                     0.000                             1.000                             0.000                               1.000                               0.000                   0.000           0.018           0.000             0.038             0.000            0.000              0.000                   0.020                     0.000                       0.030
50%       -1.000    291.000                 1.000                           0.000                             1.000                             0.000                     7.000         226.000                 43.135                           1.881                             0.894                210.000               56.865                         1.585                           0.831              205.000             41.667                       1.928                         0.811              288.000               56.818                         1.969                           1.140             398.000             1.575                    1411.000                                 6664.000                                         11464.000                          0.000         0.000         0.000       1.000      0.000       0.000        1.000      1.000                 1366.558                                2843.366                               1938.775                              3571.638                      1.000           0.000             0.000              0.000                          13.000                                          12.000                                           84.000                                          70.000                                                               0.000                                 536.000                        311.000                      3557.000                               2930.000                                    14.000                             1.000                             0.000                               1.000                               0.000                   0.000           0.112           0.000             0.450             0.000            1.000              0.000                   0.146                     1.000                       0.600
75%       -1.000    578.000                 1.000                           0.000                             1.000                             0.000                     9.000         416.000                 65.129                           3.462                             1.646                557.000               72.414                         4.204                           2.204              661.000             48.824                       6.218                         2.616              708.000               67.241                         4.839                           2.802            1399.000             5.536                    1477.000                                 6974.000                                         11464.000                          1.000         1.000         1.000       1.000      0.000       0.000        2.000      1.000                 2746.212                                3460.737                               2372.176                              3939.360                      1.000           1.000             1.000              0.000                          22.000                                          20.000                                          144.000                                         120.000                                                               1.000                                 751.000                        408.000                      4973.000                               4125.000                                    35.000                             1.000                             0.000                               1.000                               0.000                   0.000           0.699           1.000             0.852             1.000            1.000              1.000                   0.795                     1.000                       0.875
max        5.000   1000.000                 1.000                           1.000                             1.000                             1.000                    11.000        3970.000                 84.299                          33.037                            15.710               4510.000               87.500                        34.038                          17.847             2844.000             58.333                      26.752                        11.254             5228.000               80.808                        35.735                          20.689            7931.000            31.385                    2895.000                                 6974.000                                         11464.000                          1.000         1.000         1.000       1.000      1.000       1.000        2.000      2.000                 3888.445                                4529.657                               4699.074                              4869.203                      2.000           1.000             1.000              1.000                         349.000                                         209.000                                         2496.000                                        2142.000                                                              11.000                               10385.000                       1107.000                     66310.000                              55654.000                                   631.000                             1.000                             1.000                               1.000                               1.000                   1.000           0.994           1.000             0.967             1.000            1.000              1.000                   0.992                     1.000                       0.966

In [69]:
df_jobs[
    [
        'Warmth', 'Warmth_Probability', 'Warmth_actual', 'Warmth_predicted', 'Warmth_Probability_predicted',
        'Competence', 'Competence_Probability', 'Competence_actual', 'Competence_predicted', 'Competence_Probability_predicted',
    ]
].head()

   Warmth  Warmth_Probability  Warmth_actual  Warmth_predicted  Warmth_Probability_predicted  Competence  Competence_Probability  Competence_actual  Competence_predicted  Competence_Probability_predicted
0     0          0.012             NaN              NaN                     NaN                    0              0.015                 NaN                  NaN                         NaN
1     0          0.014             NaN              NaN                     NaN                    0              0.059                 NaN                  NaN                         NaN
2     0          0.291             NaN              NaN                     NaN                    1              0.637                 NaN                  NaN                         NaN
3     0          0.163             NaN              NaN                     NaN                    1              0.924                 NaN                  NaN                         NaN
4     1          0.851             NaN              NaN                     NaN                    0              0.062                 NaN                  NaN                         NaN

In [70]:
df_jobs[
    [
        'Warmth', 'Warmth_Probability', 'Warmth_actual', 'Warmth_predicted', 'Warmth_Probability_predicted',
        'Competence', 'Competence_Probability', 'Competence_actual', 'Competence_predicted', 'Competence_Probability_predicted',
    ]
].describe()

        Warmth    Warmth_Probability  Warmth_actual  Warmth_predicted  Warmth_Probability_predicted  Competence  Competence_Probability  Competence_actual  Competence_predicted  Competence_Probability_predicted
count 308583.000      308583.000        5084.000         5084.000                5084.000            308583.000        308583.000            5084.000             5084.000                    5084.000
mean       0.241           0.327           0.297            0.275                   0.359                 0.475             0.451               0.507                0.515                       0.473
std        0.427           0.366           0.457            0.447                   0.382                 0.499             0.378               0.500                0.500                       0.398
min        0.000           0.000           0.000            0.000                   0.000                 0.000             0.011               0.000                0.000                       0.011
25%        0.000           0.018           0.000            0.000                   0.020                 0.000             0.038               0.000                0.000                       0.030
50%        0.000           0.112           0.000            0.000                   0.146                 0.000             0.450               1.000                1.000                       0.600
75%        0.000           0.699           1.000            1.000                   0.795                 1.000             0.852               1.000                1.000                       0.875
max        1.000           0.994           1.000            1.000                   0.992                 1.000             0.967               1.000                1.000                       0.966

In [71]:
assert len(df_jobs) > 0 and isinstance(df_jobs, pd.DataFrame), f'ERORR: LENGTH OF DF = {len(df_jobs)}'
df_jobs.to_pickle(f'{df_save_dir}df_jobs_for_analysis.pkl')
df_jobs.to_csv(f'{df_save_dir}df_jobs_for_analysis.csv', index=False)

In [72]:
print(f'Saving classified df_jobs length {len(df_jobs)} to txt file.')
with open(f'{data_dir}df_jobs_for_analysis_len.txt', 'w') as f:
    f.write(str(len(df_jobs)))

Saving classified df_jobs length 308583 to txt file.

In [73]:
get_df_info(
    df_jobs,
    ivs_all=analysis_columns + [f'{col}_actual' for col in analysis_columns] + [f'{col}_predicted' for col in analysis_columns]
)

DF INFO:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308583 entries, 0 to 308582
Columns: 101 entries, Search Keyword to Competence_Probability_predicted
dtypes: category(2), float64(66), int64(2), object(31)
memory usage: 233.7+ MB
====================
Warmth:
--------------------
Warmth Counts:
Warmth
0    234366
1     74217
Name: count, dtype: int64
--------------------
Warmth Percentages:
Warmth
0   75.900
1   24.100
Name: proportion, dtype: float64
--------------------
Min Warmth value: 0.0
Max Warmth value: 1.0
--------------------
Warmth Mean: 0.241
--------------------
Warmth Standard Deviation: 0.427
====================
Competence:
--------------------
Competence Counts:
Competence
0    161987
1    146596
Name: count, dtype: int64
--------------------
Competence Percentages:
Competence
0   52.500
1   47.500
Name: proportion, dtype: float64
--------------------
Min Competence value: 0.0
Max Competence value: 1.0
--------------------
Competence Mean: 0.475
--------------------
Competence Standard Deviation: 0.499
====================
Warmth_actual:
--------------------
Warmth_actual Counts:
Warmth_actual
0.000    3574
1.000    1510
Name: count, dtype: int64
--------------------
Warmth_actual Percentages:
Warmth_actual
0.000   70.300
1.000   29.700
Name: proportion, dtype: float64
--------------------
Min Warmth_actual value: 0.0
Max Warmth_actual value: 1.0
--------------------
Warmth_actual Mean: 0.297
--------------------
Warmth_actual Standard Deviation: 0.457
====================
Competence_actual:
--------------------
Competence_actual Counts:
Competence_actual
1.000    2576
0.000    2508
Name: count, dtype: int64
--------------------
Competence_actual Percentages:
Competence_actual
1.000   50.700
0.000   49.300
Name: proportion, dtype: float64
--------------------
Min Competence_actual value: 0.0
Max Competence_actual value: 1.0
--------------------
Competence_actual Mean: 0.507
--------------------
Competence_actual Standard Deviation: 0.5
====================
Warmth_predicted:
--------------------
Warmth_predicted Counts:
Warmth_predicted
0.000    3684
1.000    1400
Name: count, dtype: int64
--------------------
Warmth_predicted Percentages:
Warmth_predicted
0.000   72.500
1.000   27.500
Name: proportion, dtype: float64
--------------------
Min Warmth_predicted value: 0.0
Max Warmth_predicted value: 1.0
--------------------
Warmth_predicted Mean: 0.275
--------------------
Warmth_predicted Standard Deviation: 0.447
====================
Competence_predicted:
--------------------
Competence_predicted Counts:
Competence_predicted
1.000    2618
0.000    2466
Name: count, dtype: int64
--------------------
Competence_predicted Percentages:
Competence_predicted
1.000   51.500
0.000   48.500
Name: proportion, dtype: float64
--------------------
Min Competence_predicted value: 0.0
Max Competence_predicted value: 1.0
--------------------
Competence_predicted Mean: 0.515
--------------------
Competence_predicted Standard Deviation: 0.5

In [74]:
get_df_info(
    df_jobs,
    ivs_all=classified_columns + [f'{col}_predicted' for col in classified_columns ]
)

DF INFO:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308583 entries, 0 to 308582
Columns: 101 entries, Search Keyword to Competence_Probability_predicted
dtypes: category(2), float64(66), int64(2), object(31)
memory usage: 233.7+ MB
====================
Warmth_Probability:
--------------------
Min Warmth_Probability value: 0.0
Max Warmth_Probability value: 0.994
--------------------
Warmth_Probability Mean: 0.327
--------------------
Warmth_Probability Standard Deviation: 0.366
====================
Competence_Probability:
--------------------
Min Competence_Probability value: 0.011
Max Competence_Probability value: 0.967
--------------------
Competence_Probability Mean: 0.451
--------------------
Competence_Probability Standard Deviation: 0.378
====================
Warmth_Probability_predicted:
--------------------
Min Warmth_Probability_predicted value: 0.0
Max Warmth_Probability_predicted value: 0.992
--------------------
Warmth_Probability_predicted Mean: 0.359
--------------------
Warmth_Probability_predicted Standard Deviation: 0.382
====================
Competence_Probability_predicted:
--------------------
Min Competence_Probability_predicted value: 0.011
Max Competence_Probability_predicted value: 0.966
--------------------
Competence_Probability_predicted Mean: 0.473
--------------------
Competence_Probability_predicted Standard Deviation: 0.398

In [75]:
get_df_info(
    df_jobs,
    ivs_all=dvs_all + [f'{col}_actual' for col in dvs_all if '_Probability' not in col] + [f'{col}_predicted' for col in dvs_all]
)

DF INFO:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308583 entries, 0 to 308582
Columns: 101 entries, Search Keyword to Competence_Probability_predicted
dtypes: category(2), float64(66), int64(2), object(31)
memory usage: 233.7+ MB
====================
Warmth:
--------------------
Warmth Counts:
Warmth
0    234366
1     74217
Name: count, dtype: int64
--------------------
Warmth Percentages:
Warmth
0   75.900
1   24.100
Name: proportion, dtype: float64
--------------------
Min Warmth value: 0.0
Max Warmth value: 1.0
--------------------
Warmth Mean: 0.241
--------------------
Warmth Standard Deviation: 0.427
====================
Competence:
--------------------
Competence Counts:
Competence
0    161987
1    146596
Name: count, dtype: int64
--------------------
Competence Percentages:
Competence
0   52.500
1   47.500
Name: proportion, dtype: float64
--------------------
Min Competence value: 0.0
Max Competence value: 1.0
--------------------
Competence Mean: 0.475
--------------------
Competence Standard Deviation: 0.499
====================
Warmth_Probability:
--------------------
Min Warmth_Probability value: 0.0
Max Warmth_Probability value: 0.994
--------------------
Warmth_Probability Mean: 0.327
--------------------
Warmth_Probability Standard Deviation: 0.366
====================
Competence_Probability:
--------------------
Min Competence_Probability value: 0.011
Max Competence_Probability value: 0.967
--------------------
Competence_Probability Mean: 0.451
--------------------
Competence_Probability Standard Deviation: 0.378
====================
Warmth_actual:
--------------------
Warmth_actual Counts:
Warmth_actual
0.000    3574
1.000    1510
Name: count, dtype: int64
--------------------
Warmth_actual Percentages:
Warmth_actual
0.000   70.300
1.000   29.700
Name: proportion, dtype: float64
--------------------
Min Warmth_actual value: 0.0
Max Warmth_actual value: 1.0
--------------------
Warmth_actual Mean: 0.297
--------------------
Warmth_actual Standard Deviation: 0.457
====================
Competence_actual:
--------------------
Competence_actual Counts:
Competence_actual
1.000    2576
0.000    2508
Name: count, dtype: int64
--------------------
Competence_actual Percentages:
Competence_actual
1.000   50.700
0.000   49.300
Name: proportion, dtype: float64
--------------------
Min Competence_actual value: 0.0
Max Competence_actual value: 1.0
--------------------
Competence_actual Mean: 0.507
--------------------
Competence_actual Standard Deviation: 0.5
====================
Warmth_predicted:
--------------------
Warmth_predicted Counts:
Warmth_predicted
0.000    3684
1.000    1400
Name: count, dtype: int64
--------------------
Warmth_predicted Percentages:
Warmth_predicted
0.000   72.500
1.000   27.500
Name: proportion, dtype: float64
--------------------
Min Warmth_predicted value: 0.0
Max Warmth_predicted value: 1.0
--------------------
Warmth_predicted Mean: 0.275
--------------------
Warmth_predicted Standard Deviation: 0.447
====================
Competence_predicted:
--------------------
Competence_predicted Counts:
Competence_predicted
1.000    2618
0.000    2466
Name: count, dtype: int64
--------------------
Competence_predicted Percentages:
Competence_predicted
1.000   51.500
0.000   48.500
Name: proportion, dtype: float64
--------------------
Min Competence_predicted value: 0.0
Max Competence_predicted value: 1.0
--------------------
Competence_predicted Mean: 0.515
--------------------
Competence_predicted Standard Deviation: 0.5
====================
Warmth_Probability_predicted:
--------------------
Min Warmth_Probability_predicted value: 0.0
Max Warmth_Probability_predicted value: 0.992
--------------------
Warmth_Probability_predicted Mean: 0.359
--------------------
Warmth_Probability_predicted Standard Deviation: 0.382
====================
Competence_Probability_predicted:
--------------------
Min Competence_Probability_predicted value: 0.011
Max Competence_Probability_predicted value: 0.966
--------------------
Competence_Probability_predicted Mean: 0.473
--------------------
Competence_Probability_predicted Standard Deviation: 0.398

In [76]:
df_jobs[['Job ID', 'Search Keyword', 'Sector', 'Warmth_Probability', 'Competence_Probability', 'Job Description spacy_sentencized',]].drop_duplicates(subset=['Job Description spacy_sentencized']).loc[
    (df_jobs['Warmth_Probability'] > df_jobs['Warmth_Probability'].max() - 0.05)
    & (df_jobs['Competence_Probability'] < df_jobs['Competence_Probability'].min() + 0.05)
][['Job ID', 'Warmth_Probability', 'Competence_Probability', 'Job Description spacy_sentencized',]].sort_values(by='Competence_Probability', ascending=True).sort_values(by='Warmth_Probability', ascending=False).to_csv(f'{data_dir}Job Description spacy_sentencized_with_highest_warmth_probability_and_lowest_competence_probability.csv', index=False)

In [77]:
df_jobs[['Job ID', 'Search Keyword', 'Sector', 'Competence_Probability', 'Warmth_Probability', 'Job Description spacy_sentencized',]].drop_duplicates(subset=['Job Description spacy_sentencized']).loc[
    (df_jobs['Competence_Probability'] > df_jobs['Competence_Probability'].max() - 0.05)
    & (df_jobs['Warmth_Probability'] < df_jobs['Warmth_Probability'].min() + 0.05)
][['Job ID', 'Competence_Probability', 'Warmth_Probability', 'Job Description spacy_sentencized',]].sort_values(by='Warmth_Probability', ascending=True).sort_values(by='Competence_Probability', ascending=False).to_csv(f'{data_dir}Job Description spacy_sentencized_with_highest_competence_probability_and_lowest_warmth_probability.csv', index=False)

### Save dataframe

In [78]:
assert len(df_jobs) > 0 and isinstance(df_jobs, pd.DataFrame) and all(col in df_jobs.columns for col in dvs_all), f'ERORR: LENGTH OF DF = {len(df_jobs)}'
df_jobs.to_pickle(f'{df_save_dir}df_jobs_for_analysis.pkl')
df_jobs.to_csv(f'{df_save_dir}df_jobs_for_analysis.csv', index=False)

In [79]:
print(f'Saving classified df_jobs length {len(df_jobs)} to txt file.')
with open(f'{data_dir}df_jobs_for_analysis_len.txt', 'w') as f:
    f.write(str(len(df_jobs)))

Saving classified df_jobs length 308583 to txt file.

In [80]:
assert len(df_manual) > 0 and isinstance(df_manual, pd.DataFrame) and all(col in df_manual.columns for col in ['Warmth_predicted', 'Warmth_Probability_predicted', 'Competence_predicted', 'Competence_Probability_predicted']), f'ERORR: LENGTH OF DF = {len(df_manual)}'
df_manual.to_pickle(f'{df_save_dir}df_manual_for_analysis.pkl')
df_manual.to_csv(f'{df_save_dir}df_manual_for_analysis.csv', index=False)

In [81]:
print(f'Saving classified df_manual length {len(df_manual)} to txt file.')
with open(f'{data_dir}df_manual_for_analysis_len.txt', 'w') as f:
    f.write(str(len(df_manual)))

Saving classified df_manual length 5084 to txt file.